export const hotel_details = {

        hotel1: [
        { checkInDate: "12/06/2024" ,
        NoOfChild:1,
        NoOfAdults:3,
        ChildAge:[3],
        room:{
            Amenities: ['Breakfast buffet', 'Free self parking', 'Free breakfast'],
            Amenity: ['Breakfast buffet', 'Free self parking', 'Free breakfast'],
            AvailabilityType: 'Confirm',
            BedTypes: [],
            CancellationPolicies: [
                {Charge: 4332, ChargeType: 1, Currency: 'INR', FromDate: '2024-02-18T00:00:00', ToDate: '2024-05-30T23:59:59'},
                {Charge: 100, ChargeType: 2, Currency: 'INR', FromDate: '2024-05-31T00:00:00', ToDate: '2024-06-01T23:59:59'},
                {Charge: 100, ChargeType: 2, Currency: 'INR', FromDate: '2024-06-02T00:00:00', ToDate: '2024-06-14T23:59:59'}
            ],
            CancellationPolicy: "Deluxe Room, 2 Twin Beds, Nonsmoking#^#INR 4332.00 will be charged, If cancelled between 18-Feb-2024 00:00:00 and 30-May-2024 23:59:59.|100.00% of the total amount will be charged, If cancelled between 31-May-2024 00:00:00 and 01-Jun-2024 23:59:59.|100.00% of the total amount will be charged, If cancelled between 02-Jun-2024 00:00:00 and 14-Jun-2024 23:59:59.|#!#",
            ChildCount: 0,
            DayRates: [
                { Amount: 2961.85, Date: '2024-06-10T00:00:00' },
            ],
            HotelSupplements: [],
            Inclusion: ['Breakfast buffet', 'Free self parking', 'Free breakfast'],
            InfoSource: 'FixedCombination',
            IsPANMandatory: true,
            IsPassportMandatory: false,
            IsPerStay: false,
            LastCancellationDate: '2024-02-17T00:00:00',
            LastVoucherDate: '2024-02-17T00:00:00',
            Price: {
                CurrencyCode: 'INR',
                RoomPrice: 2911.34,
                Tax: 667.08,
                ExtraGuestCharge: 0,
                ChildCharge: 0,
                PublishedPrice:2452,
                // Add other properties as needed
            },
            RatePlan: 0,
            RatePlanCode: '201289856|206249157|37341|127',
            RatePlanName: 'Breakfast buffet, Free self parking Free breakfast',
            RequireAllPaxDetails: true,
            RoomDescription: 'Deluxe Room, 2 Twin Beds, Nonsmoking',
            RoomId: 0,
            RoomIndex: 3,
            RoomPromotion: 'Private sale: save 5%|',
            RoomStatus: 0,
            RoomTypeCode: '201289856|206249157$37341^^2^^201289856|206249157|37341|127~!:~2',
            RoomTypeName: 'Deluxe Room, 2 Twin Beds, Nonsmoking',
            SequenceNo: 'TH~~9989080~1',
            SmokingPreference: 'NoPreference',
            SupplierPrice: null,
        },
        search: {
            "IsHotDeal": false,
            "ResultIndex": 7,
            "HotelCode": "1093192",
            "HotelName": "Aveda Ludhiana",
            "HotelCategory": "",
            "StarRating": 4,
            "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
            "HotelPromotion": "",
            "HotelPolicy": "",
            "Price": {
                "CurrencyCode": "INR",
                "RoomPrice": 28282.75,
                "Tax": 0.00,
                "ExtraGuestCharge": 0.00,
                "ChildCharge": 0.00,
                "OtherCharges": 7856.50,
                "Discount": 0.00,
                "PublishedPrice": 39281.69,
                "PublishedPriceRoundedOff": 39282,
                "OfferedPrice": 36139.25,
                "OfferedPriceRoundedOff": 36139,
                "AgentCommission": 3142.44,
                "AgentMarkUp": 0.00,
                "ServiceTax": 1414.17,
                "TCS": 0.00,
                "TDS": 0.00,
                "ServiceCharge": 0,
                "TotalGSTAmount": 1414.1693,
                "GST": {
                    "CGSTAmount": 0.0000,
                    "CGSTRate": 0,
                    "CessAmount": 0.0000,
                    "CessRate": 0,
                    "IGSTAmount": 1414.1693,
                    "IGSTRate": 18,
                    "SGSTAmount": 0.0000,
                    "SGSTRate": 0,
                    "TaxableAmount": 7856.50
                }
            },
            "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
            "HotelAddress": "Humbran Road Ludhiana 141007 , ",
            "HotelContactNo": "",
            "HotelMap": null,
            "Latitude": "",
            "Longitude": "",
            "HotelLocation": null,
            "SupplierPrice": null,
            "RoomDetails": []
        },
        cityName:'Delhi'},
        { checkInDate: "12/06/2024" ,
        NoOfChild:1,
        NoOfAdults:3,
        ChildAge:[3],
        room:{
            Amenities: ['Breakfast buffet', 'Free self parking', 'Free breakfast'],
            AvailabilityType: 'Confirm',
            BedTypes: [],
            CancellationPolicies: [
                {
                Charge: 4332,
                ChargeType: 1,
                Currency: 'INR',
                FromDate: '2024-02-18T00:00:00',
                ToDate: '2024-05-30T23:59:59',
                },
                {
                Charge: 100,
                ChargeType: 2,
                Currency: 'INR',
                FromDate: '2024-05-31T00:00:00',
                ToDate: '2024-06-01T23:59:59',
                },
                {
                Charge: 100,
                ChargeType: 2,
                Currency: 'INR',
                FromDate: '2024-06-02T00:00:00',
                ToDate: '2024-06-14T23:59:59',
                },
            ],
            CancellationPolicy:
                'Deluxe Room, 1 King Bed, Nonsmoking#^#INR 4332.00 will be charged, If cancelled between 18-Feb-2024 00:00:00 and 30-May-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 31-May-2024 00:00:00 and 01-Jun-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 02-Jun-2024 00:00:00 and 14-Jun-2024 23:59:59.|#!#',
            ChildCount: 0,
            DayRates: [
                { Amount: 1455.67, Date: '2024-06-12T00:00:00' },
                { Amount: 1455.67, Date: '2024-06-13T00:00:00' },
            ],
            HotelSupplements: [],
            Inclusion: ['Breakfast buffet', 'Free self parking', 'Free breakfast'],
            InfoSource: 'FixedCombination',
            IsPANMandatory: true,
            IsPassportMandatory: false,
            IsPerStay: false,
            LastCancellationDate: '2024-02-17T00:00:00',
            LastVoucherDate: '2024-02-17T00:00:00',
            Price: {
                AgentCommission: 154.86,
                AgentMarkUp: 0,
                PublishedPrice:5,
                // Add other properties as needed
            },
            RatePlan: 0,
            RatePlanCode: '201289856|206249157|37321|127',
            RatePlanName: 'Breakfast buffet, Free self parking Free breakfast',
            RequireAllPaxDetails: true,
            RoomDescription: 'Deluxe Room, 1 King Bed, Nonsmoking',
            RoomId: 0,
            RoomIndex: 4,
            RoomPromotion: 'Private sale: save 5%|',
            RoomStatus: 0,
            RoomTypeCode: '201289856|206249157$37321^^2^^201289856|206249157|37321|127~!:~4',
            RoomTypeName: 'Deluxe Room, 1 King Bed, Nonsmoking',
            SequenceNo: 'TH~~9989080~2',
            SmokingPreference: 'NoPreference',
            SupplierPrice: null,
        },
        search: {
            "IsHotDeal": false,
            "ResultIndex": 7,
            "HotelCode": "1093192",
            "HotelName": "Aveda Ludhiana",
            "HotelCategory": "",
            "StarRating": 4,
            "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
            "HotelPromotion": "",
            "HotelPolicy": "",
            "Price": {
                "CurrencyCode": "INR",
                "RoomPrice": 28282.75,
                "Tax": 0.00,
                "ExtraGuestCharge": 0.00,
                "ChildCharge": 0.00,
                "OtherCharges": 7856.50,
                "Discount": 0.00,
                "PublishedPrice": 39281.69,
                "PublishedPriceRoundedOff": 39282,
                "OfferedPrice": 36139.25,
                "OfferedPriceRoundedOff": 36139,
                "AgentCommission": 3142.44,
                "AgentMarkUp": 0.00,
                "ServiceTax": 1414.17,
                "TCS": 0.00,
                "TDS": 0.00,
                "ServiceCharge": 0,
                "TotalGSTAmount": 1414.1693,
                "GST": {
                    "CGSTAmount": 0.0000,
                    "CGSTRate": 0,
                    "CessAmount": 0.0000,
                    "CessRate": 0,
                    "IGSTAmount": 1414.1693,
                    "IGSTRate": 18,
                    "SGSTAmount": 0.0000,
                    "SGSTRate": 0,
                    "TaxableAmount": 7856.50
                }
            },
            "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
            "HotelAddress": "Humbran Road Ludhiana 141007 , ",
            "HotelContactNo": "",
            "HotelMap": null,
            "Latitude": "",
            "Longitude": "",
            "HotelLocation": null,
            "SupplierPrice": null,
            "RoomDetails": []
        },
        cityName:'Delhi'}
        ],
        hotel2:[
            {checkInDate:"10/06/2024",
            NoOfAdults:3,
            NoOfChild:1,
            ChildAge:[3],
            room:{
                Amenities: ['BED AND BREAKFAST'],
                Amenity: ['Internet access'],
                AvailabilityType: 'Confirm',
                BedTypes: [/* Add bed types data */],
                CancellationPolicies: [
                    {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-02-13T00:00:00',
                    ToDate: '2024-06-09T23:59:59',
                    },
                    {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-06-10T00:00:00',
                    ToDate: '2024-06-12T23:59:59',
                    },
                ],
                CancellationPolicy:
                    'GRAND SUPERIOR ROOM#^#100.00% of total amount will be charged, If cancelled between 13-Feb-2024 00:00:00 and 09-Jun-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 10-Jun-2024 00:00:00 and 12-Jun-2024 23:59:59.|#!#',
                ChildCount: 0,
                DayRates: [
                    { Amount: 2961.85, Date: '2024-06-10T00:00:00' },
                    { Amount: 2961.85, Date: '2024-06-11T00:00:00' },
                ],
                HotelSupplements: [],
                Inclusion: ['BED AND BREAKFAST'],
                InfoSource: 'OpenCombination',
                IsPANMandatory: true,
                IsPassportMandatory: false,
                IsPerStay: false,
                LastCancellationDate: '2024-02-12T23:59:59',
                LastVoucherDate: '2024-02-13T00:00:00',
                Price: {
                    AgentCommission: 311.77,
                    AgentMarkUp: 0,
                    PublishedPrice:435,
                    // Add other properties as needed
                },
                // Add other properties as needed
                RatePlan: 13,
                RatePlanCode: '20240610|20240612|W|325|583574|DBL.SU-2|NRF-BAR-BB|BB||1~1~1|3|N^#^2',
                RatePlanName: 'Breakfast',
                RequireAllPaxDetails: true,
                RoomDescription: 'GRAND SUPERIOR ROOM',
                RoomId: 0,
                RoomIndex: 2,
                RoomPromotion: '',
                RoomStatus: 0,
                RoomTypeCode: 'DBL.SU-2_2_20240610|20240612|W|325|583574|DBL.SU-2|NRF-BAR-BB|BB||1~1~1|3|N',
                RoomTypeName: 'GRAND SUPERIOR ROOM',
                SequenceNo: '2',
                SmokingPreference: 'NoPreference',
                SupplierPrice: null,
            },
            search: {
                "IsHotDeal": false,
                "ResultIndex": 7,
                "HotelCode": "1093192",
                "HotelName": "Aveda Ludhiana",
                "HotelCategory": "",
                "StarRating": 4,
                "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
                "HotelPromotion": "",
                "HotelPolicy": "",
                "Price": {
                    "CurrencyCode": "INR",
                    "RoomPrice": 28282.75,
                    "Tax": 0.00,
                    "ExtraGuestCharge": 0.00,
                    "ChildCharge": 0.00,
                    "OtherCharges": 7856.50,
                    "Discount": 0.00,
                    "PublishedPrice": 39281.69,
                    "PublishedPriceRoundedOff": 39282,
                    "OfferedPrice": 36139.25,
                    "OfferedPriceRoundedOff": 36139,
                    "AgentCommission": 3142.44,
                    "AgentMarkUp": 0.00,
                    "ServiceTax": 1414.17,
                    "TCS": 0.00,
                    "TDS": 0.00,
                    "ServiceCharge": 0,
                    "TotalGSTAmount": 1414.1693,
                    "GST": {
                        "CGSTAmount": 0.0000,
                        "CGSTRate": 0,
                        "CessAmount": 0.0000,
                        "CessRate": 0,
                        "IGSTAmount": 1414.1693,
                        "IGSTRate": 18,
                        "SGSTAmount": 0.0000,
                        "SGSTRate": 0,
                        "TaxableAmount": 7856.50
                    }
                },
                "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
                "HotelAddress": "Humbran Road Ludhiana 141007 , ",
                "HotelContactNo": "",
                "HotelMap": null,
                "Latitude": "",
                "Longitude": "",
                "HotelLocation": null,
                "SupplierPrice": null,
                "RoomDetails": []
            },
        cityName:'Ahmedabad'},
            {checkInDate:"10/06/2024",
            NoOfAdults:3,
            NoOfChild:1,
            ChildAge:[3],
            room:{
                Amenities: ['BED AND BREAKFAST'],
                Amenity: [
                  'Mini fridge',
                  'Desk',
                  'Shower',
                  'Cable TV',
                  'Internet access',
                  'Direct dial telephone',
                  'Slippers',
                  'Smoke detector',
                  'Wake-up service',
                  'Fridge',
                ],
                AvailabilityType: 'Confirm',
                BedTypes: [/* Add bed types data */],
                CancellationPolicies: [
                  {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-02-13T00:00:00',
                    ToDate: '2024-06-09T23:59:59',
                  },
                  {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-06-10T00:00:00',
                    ToDate: '2024-06-12T23:59:59',
                  },
                ],
                CancellationPolicy:
                  'Superior Room Twin#^#100.00% of total amount will be charged, If cancelled between 13-Feb-2024 00:00:00 and 09-Jun-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 10-Jun-2024 00:00:00 and 12-Jun-2024 23:59:59.|#!#',
                ChildCount: 0,
                DayRates: [
                  { Amount: 2961.85, Date: '2024-06-10T00:00:00' },
                  { Amount: 2961.85, Date: '2024-06-11T00:00:00' },
                ],
                HotelSupplements: [],
                Inclusion: ['BED AND BREAKFAST'],
                InfoSource: 'OpenCombination',
                IsPANMandatory: true,
                IsPassportMandatory: false,
                IsPerStay: false,
                LastCancellationDate: '2024-02-12T23:59:59',
                LastVoucherDate: '2024-02-13T00:00:00',
                Price: {
                  AgentCommission: 311.77,
                  AgentMarkUp: 0,
                  PublishedPrice:3255,
                  // Add other properties as needed
                },
                // Add other properties as needed
                RatePlan: 13,
                RatePlanCode: '20240610|20240612|W|325|583574|TWN.SU-1|NRF-BAR-BB|BB||1~1~1|3|N^#^2',
                RatePlanName: 'Breakfast',
                RequireAllPaxDetails: true,
                RoomDescription: 'Superior Room Twin',
                RoomId: 0,
                RoomIndex: 3,
                RoomPromotion: '',
                RoomStatus: 0,
                RoomTypeCode: 'TWN.SU-1_2_20240610|20240612|W|325|583574|TWN.SU-1|NRF-BAR-BB|BB||1~1~1|3|N',
                RoomTypeName: 'Superior Room Twin',
                SequenceNo: '2',
                SmokingPreference: 'NoPreference',
                SupplierPrice: null,
            },
            search: {
                "IsHotDeal": false,
                "ResultIndex": 7,
                "HotelCode": "1093192",
                "HotelName": "Aveda Ludhiana",
                "HotelCategory": "",
                "StarRating": 4,
                "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
                "HotelPromotion": "",
                "HotelPolicy": "",
                "Price": {
                    "CurrencyCode": "INR",
                    "RoomPrice": 28282.75,
                    "Tax": 0.00,
                    "ExtraGuestCharge": 0.00,
                    "ChildCharge": 0.00,
                    "OtherCharges": 7856.50,
                    "Discount": 0.00,
                    "PublishedPrice": 39281.69,
                    "PublishedPriceRoundedOff": 39282,
                    "OfferedPrice": 36139.25,
                    "OfferedPriceRoundedOff": 36139,
                    "AgentCommission": 3142.44,
                    "AgentMarkUp": 0.00,
                    "ServiceTax": 1414.17,
                    "TCS": 0.00,
                    "TDS": 0.00,
                    "ServiceCharge": 0,
                    "TotalGSTAmount": 1414.1693,
                    "GST": {
                        "CGSTAmount": 0.0000,
                        "CGSTRate": 0,
                        "CessAmount": 0.0000,
                        "CessRate": 0,
                        "IGSTAmount": 1414.1693,
                        "IGSTRate": 18,
                        "SGSTAmount": 0.0000,
                        "SGSTRate": 0,
                        "TaxableAmount": 7856.50
                    }
                },
                "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
                "HotelAddress": "Humbran Road Ludhiana 141007 , ",
                "HotelContactNo": "",
                "HotelMap": null,
                "Latitude": "",
                "Longitude": "",
                "HotelLocation": null,
                "SupplierPrice": null,
                "RoomDetails": []
            },
        cityName:'Ahmedabad'},
        ],
        hotel3:[
            {checkInDate:"10/06/2024",
            NoOfAdults:3,
            NoOfChild:1,
            ChildAge:[3],
            room:{
                Amenities: ['BED AND BREAKFAST'],
                Amenity: ['Internet access'],
                AvailabilityType: 'Confirm',
                BedTypes: [/* Add bed types data */],
                CancellationPolicies: [
                    {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-02-13T00:00:00',
                    ToDate: '2024-06-09T23:59:59',
                    },
                    {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-06-10T00:00:00',
                    ToDate: '2024-06-12T23:59:59',
                    },
                ],
                CancellationPolicy:
                    'GRAND SUPERIOR ROOM#^#100.00% of total amount will be charged, If cancelled between 13-Feb-2024 00:00:00 and 09-Jun-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 10-Jun-2024 00:00:00 and 12-Jun-2024 23:59:59.|#!#',
                ChildCount: 0,
                DayRates: [
                    { Amount: 2961.85, Date: '2024-06-10T00:00:00' },
                    { Amount: 2961.85, Date: '2024-06-11T00:00:00' },
                ],
                HotelSupplements: [],
                Inclusion: ['BED AND BREAKFAST'],
                InfoSource: 'OpenCombination',
                IsPANMandatory: true,
                IsPassportMandatory: false,
                IsPerStay: false,
                LastCancellationDate: '2024-02-12T23:59:59',
                LastVoucherDate: '2024-02-13T00:00:00',
                Price: {
                    AgentCommission: 311.77,
                    AgentMarkUp: 0,
                    PublishedPrice:435,
                    // Add other properties as needed
                },
                // Add other properties as needed
                RatePlan: 13,
                RatePlanCode: '20240610|20240612|W|325|583574|DBL.SU-2|NRF-BAR-BB|BB||1~1~1|3|N^#^2',
                RatePlanName: 'Breakfast',
                RequireAllPaxDetails: true,
                RoomDescription: 'GRAND SUPERIOR ROOM',
                RoomId: 0,
                RoomIndex: 2,
                RoomPromotion: '',
                RoomStatus: 0,
                RoomTypeCode: 'DBL.SU-2_2_20240610|20240612|W|325|583574|DBL.SU-2|NRF-BAR-BB|BB||1~1~1|3|N',
                RoomTypeName: 'GRAND SUPERIOR ROOM',
                SequenceNo: '2',
                SmokingPreference: 'NoPreference',
                SupplierPrice: null,
            },
            search: {
                "IsHotDeal": false,
                "ResultIndex": 7,
                "HotelCode": "1093192",
                "HotelName": "Aveda Ludhiana",
                "HotelCategory": "",
                "StarRating": 4,
                "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
                "HotelPromotion": "",
                "HotelPolicy": "",
                "Price": {
                    "CurrencyCode": "INR",
                    "RoomPrice": 28282.75,
                    "Tax": 0.00,
                    "ExtraGuestCharge": 0.00,
                    "ChildCharge": 0.00,
                    "OtherCharges": 7856.50,
                    "Discount": 0.00,
                    "PublishedPrice": 39281.69,
                    "PublishedPriceRoundedOff": 39282,
                    "OfferedPrice": 36139.25,
                    "OfferedPriceRoundedOff": 36139,
                    "AgentCommission": 3142.44,
                    "AgentMarkUp": 0.00,
                    "ServiceTax": 1414.17,
                    "TCS": 0.00,
                    "TDS": 0.00,
                    "ServiceCharge": 0,
                    "TotalGSTAmount": 1414.1693,
                    "GST": {
                        "CGSTAmount": 0.0000,
                        "CGSTRate": 0,
                        "CessAmount": 0.0000,
                        "CessRate": 0,
                        "IGSTAmount": 1414.1693,
                        "IGSTRate": 18,
                        "SGSTAmount": 0.0000,
                        "SGSTRate": 0,
                        "TaxableAmount": 7856.50
                    }
                },
                "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
                "HotelAddress": "Humbran Road Ludhiana 141007 , ",
                "HotelContactNo": "",
                "HotelMap": null,
                "Latitude": "",
                "Longitude": "",
                "HotelLocation": null,
                "SupplierPrice": null,
                "RoomDetails": []
            },
        cityName:'Kolkata'},
            {checkInDate:"10/06/2024",
            NoOfAdults:3,
            NoOfChild:1,
            ChildAge:[3],
            room:{
                Amenities: ['BED AND BREAKFAST'],
                Amenity: [
                  'Mini fridge',
                  'Desk',
                  'Shower',
                  'Cable TV',
                  'Internet access',
                  'Direct dial telephone',
                  'Slippers',
                  'Smoke detector',
                  'Wake-up service',
                  'Fridge',
                ],
                AvailabilityType: 'Confirm',
                BedTypes: [/* Add bed types data */],
                CancellationPolicies: [
                  {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-02-13T00:00:00',
                    ToDate: '2024-06-09T23:59:59',
                  },
                  {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-06-10T00:00:00',
                    ToDate: '2024-06-12T23:59:59',
                  },
                ],
                CancellationPolicy:
                  'Superior Room Twin#^#100.00% of total amount will be charged, If cancelled between 13-Feb-2024 00:00:00 and 09-Jun-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 10-Jun-2024 00:00:00 and 12-Jun-2024 23:59:59.|#!#',
                ChildCount: 0,
                DayRates: [
                  { Amount: 2961.85, Date: '2024-06-10T00:00:00' },
                  { Amount: 2961.85, Date: '2024-06-11T00:00:00' },
                ],
                HotelSupplements: [],
                Inclusion: ['BED AND BREAKFAST'],
                InfoSource: 'OpenCombination',
                IsPANMandatory: true,
                IsPassportMandatory: false,
                IsPerStay: false,
                LastCancellationDate: '2024-02-12T23:59:59',
                LastVoucherDate: '2024-02-13T00:00:00',
                Price: {
                  AgentCommission: 311.77,
                  AgentMarkUp: 0,
                  PublishedPrice:3255,
                  // Add other properties as needed
                },
                // Add other properties as needed
                RatePlan: 13,
                RatePlanCode: '20240610|20240612|W|325|583574|TWN.SU-1|NRF-BAR-BB|BB||1~1~1|3|N^#^2',
                RatePlanName: 'Breakfast',
                RequireAllPaxDetails: true,
                RoomDescription: 'Superior Room Twin',
                RoomId: 0,
                RoomIndex: 3,
                RoomPromotion: '',
                RoomStatus: 0,
                RoomTypeCode: 'TWN.SU-1_2_20240610|20240612|W|325|583574|TWN.SU-1|NRF-BAR-BB|BB||1~1~1|3|N',
                RoomTypeName: 'Superior Room Twin',
                SequenceNo: '2',
                SmokingPreference: 'NoPreference',
                SupplierPrice: null,
            },
            search: {
                "IsHotDeal": false,
                "ResultIndex": 7,
                "HotelCode": "1093192",
                "HotelName": "Aveda Ludhiana",
                "HotelCategory": "",
                "StarRating": 4,
                "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
                "HotelPromotion": "",
                "HotelPolicy": "",
                "Price": {
                    "CurrencyCode": "INR",
                    "RoomPrice": 28282.75,
                    "Tax": 0.00,
                    "ExtraGuestCharge": 0.00,
                    "ChildCharge": 0.00,
                    "OtherCharges": 7856.50,
                    "Discount": 0.00,
                    "PublishedPrice": 39281.69,
                    "PublishedPriceRoundedOff": 39282,
                    "OfferedPrice": 36139.25,
                    "OfferedPriceRoundedOff": 36139,
                    "AgentCommission": 3142.44,
                    "AgentMarkUp": 0.00,
                    "ServiceTax": 1414.17,
                    "TCS": 0.00,
                    "TDS": 0.00,
                    "ServiceCharge": 0,
                    "TotalGSTAmount": 1414.1693,
                    "GST": {
                        "CGSTAmount": 0.0000,
                        "CGSTRate": 0,
                        "CessAmount": 0.0000,
                        "CessRate": 0,
                        "IGSTAmount": 1414.1693,
                        "IGSTRate": 18,
                        "SGSTAmount": 0.0000,
                        "SGSTRate": 0,
                        "TaxableAmount": 7856.50
                    }
                },
                "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
                "HotelAddress": "Humbran Road Ludhiana 141007 , ",
                "HotelContactNo": "",
                "HotelMap": null,
                "Latitude": "",
                "Longitude": "",
                "HotelLocation": null,
                "SupplierPrice": null,
                "RoomDetails": []
            },
        cityName:'Kolkata'},
        ],
        hotel4:[
            {checkInDate:"10/06/2024",
            NoOfAdults:3,
            NoOfChild:1,
            ChildAge:[3],
            room:{
                Amenities: ['BED AND BREAKFAST'],
                Amenity: ['Internet access'],
                AvailabilityType: 'Confirm',
                BedTypes: [/* Add bed types data */],
                CancellationPolicies: [
                    {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-02-13T00:00:00',
                    ToDate: '2024-06-09T23:59:59',
                    },
                    {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-06-10T00:00:00',
                    ToDate: '2024-06-12T23:59:59',
                    },
                ],
                CancellationPolicy:
                    'GRAND SUPERIOR ROOM#^#100.00% of total amount will be charged, If cancelled between 13-Feb-2024 00:00:00 and 09-Jun-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 10-Jun-2024 00:00:00 and 12-Jun-2024 23:59:59.|#!#',
                ChildCount: 0,
                DayRates: [
                    { Amount: 2961.85, Date: '2024-06-10T00:00:00' },
                    { Amount: 2961.85, Date: '2024-06-11T00:00:00' },
                ],
                HotelSupplements: [],
                Inclusion: ['BED AND BREAKFAST'],
                InfoSource: 'OpenCombination',
                IsPANMandatory: true,
                IsPassportMandatory: false,
                IsPerStay: false,
                LastCancellationDate: '2024-02-12T23:59:59',
                LastVoucherDate: '2024-02-13T00:00:00',
                Price: {
                    AgentCommission: 311.77,
                    AgentMarkUp: 0,
                    PublishedPrice:435,
                    // Add other properties as needed
                },
                // Add other properties as needed
                RatePlan: 13,
                RatePlanCode: '20240610|20240612|W|325|583574|DBL.SU-2|NRF-BAR-BB|BB||1~1~1|3|N^#^2',
                RatePlanName: 'Breakfast',
                RequireAllPaxDetails: true,
                RoomDescription: 'GRAND SUPERIOR ROOM',
                RoomId: 0,
                RoomIndex: 2,
                RoomPromotion: '',
                RoomStatus: 0,
                RoomTypeCode: 'DBL.SU-2_2_20240610|20240612|W|325|583574|DBL.SU-2|NRF-BAR-BB|BB||1~1~1|3|N',
                RoomTypeName: 'GRAND SUPERIOR ROOM',
                SequenceNo: '2',
                SmokingPreference: 'NoPreference',
                SupplierPrice: null,
            },
            search: {
                "IsHotDeal": false,
                "ResultIndex": 7,
                "HotelCode": "1093192",
                "HotelName": "Aveda Ludhiana",
                "HotelCategory": "",
                "StarRating": 4,
                "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
                "HotelPromotion": "",
                "HotelPolicy": "",
                "Price": {
                    "CurrencyCode": "INR",
                    "RoomPrice": 28282.75,
                    "Tax": 0.00,
                    "ExtraGuestCharge": 0.00,
                    "ChildCharge": 0.00,
                    "OtherCharges": 7856.50,
                    "Discount": 0.00,
                    "PublishedPrice": 39281.69,
                    "PublishedPriceRoundedOff": 39282,
                    "OfferedPrice": 36139.25,
                    "OfferedPriceRoundedOff": 36139,
                    "AgentCommission": 3142.44,
                    "AgentMarkUp": 0.00,
                    "ServiceTax": 1414.17,
                    "TCS": 0.00,
                    "TDS": 0.00,
                    "ServiceCharge": 0,
                    "TotalGSTAmount": 1414.1693,
                    "GST": {
                        "CGSTAmount": 0.0000,
                        "CGSTRate": 0,
                        "CessAmount": 0.0000,
                        "CessRate": 0,
                        "IGSTAmount": 1414.1693,
                        "IGSTRate": 18,
                        "SGSTAmount": 0.0000,
                        "SGSTRate": 0,
                        "TaxableAmount": 7856.50
                    }
                },
                "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
                "HotelAddress": "Humbran Road Ludhiana 141007 , ",
                "HotelContactNo": "",
                "HotelMap": null,
                "Latitude": "",
                "Longitude": "",
                "HotelLocation": null,
                "SupplierPrice": null,
                "RoomDetails": []
            },
        cityName:'Mumbai'},
            {checkInDate:"10/06/2024",
            NoOfAdults:3,
            NoOfChild:1,
            ChildAge:[3],
            room:{
                Amenities: ['BED AND BREAKFAST'],
                Amenity: [
                  'Mini fridge',
                  'Desk',
                  'Shower',
                  'Cable TV',
                  'Internet access',
                  'Direct dial telephone',
                  'Slippers',
                  'Smoke detector',
                  'Wake-up service',
                  'Fridge',
                ],
                AvailabilityType: 'Confirm',
                BedTypes: [/* Add bed types data */],
                CancellationPolicies: [
                  {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-02-13T00:00:00',
                    ToDate: '2024-06-09T23:59:59',
                  },
                  {
                    Charge: 100,
                    ChargeType: 2,
                    Currency: 'INR',
                    FromDate: '2024-06-10T00:00:00',
                    ToDate: '2024-06-12T23:59:59',
                  },
                ],
                CancellationPolicy:
                  'Superior Room Twin#^#100.00% of total amount will be charged, If cancelled between 13-Feb-2024 00:00:00 and 09-Jun-2024 23:59:59.|100.00% of total amount will be charged, If cancelled between 10-Jun-2024 00:00:00 and 12-Jun-2024 23:59:59.|#!#',
                ChildCount: 0,
                DayRates: [
                  { Amount: 2961.85, Date: '2024-06-10T00:00:00' },
                  { Amount: 2961.85, Date: '2024-06-11T00:00:00' },
                ],
                HotelSupplements: [],
                Inclusion: ['BED AND BREAKFAST'],
                InfoSource: 'OpenCombination',
                IsPANMandatory: true,
                IsPassportMandatory: false,
                IsPerStay: false,
                LastCancellationDate: '2024-02-12T23:59:59',
                LastVoucherDate: '2024-02-13T00:00:00',
                Price: {
                  AgentCommission: 311.77,
                  AgentMarkUp: 0,
                  PublishedPrice:3255,
                  // Add other properties as needed
                },
                // Add other properties as needed
                RatePlan: 13,
                RatePlanCode: '20240610|20240612|W|325|583574|TWN.SU-1|NRF-BAR-BB|BB||1~1~1|3|N^#^2',
                RatePlanName: 'Breakfast',
                RequireAllPaxDetails: true,
                RoomDescription: 'Superior Room Twin',
                RoomId: 0,
                RoomIndex: 3,
                RoomPromotion: '',
                RoomStatus: 0,
                RoomTypeCode: 'TWN.SU-1_2_20240610|20240612|W|325|583574|TWN.SU-1|NRF-BAR-BB|BB||1~1~1|3|N',
                RoomTypeName: 'Superior Room Twin',
                SequenceNo: '2',
                SmokingPreference: 'NoPreference',
                SupplierPrice: null,
            },
            search: {
                "IsHotDeal": false,
                "ResultIndex": 7,
                "HotelCode": "1093192",
                "HotelName": "Aveda Ludhiana",
                "HotelCategory": "",
                "StarRating": 4,
                "HotelDescription": "Property Location Located in Ludhiana, Hotel Nirvana is in the suburbs and convenient to Punjab Rural Heritage Museum and Punjab Agricultural University.  This   ",
                "HotelPromotion": "",
                "HotelPolicy": "",
                "Price": {
                    "CurrencyCode": "INR",
                    "RoomPrice": 28282.75,
                    "Tax": 0.00,
                    "ExtraGuestCharge": 0.00,
                    "ChildCharge": 0.00,
                    "OtherCharges": 7856.50,
                    "Discount": 0.00,
                    "PublishedPrice": 39281.69,
                    "PublishedPriceRoundedOff": 39282,
                    "OfferedPrice": 36139.25,
                    "OfferedPriceRoundedOff": 36139,
                    "AgentCommission": 3142.44,
                    "AgentMarkUp": 0.00,
                    "ServiceTax": 1414.17,
                    "TCS": 0.00,
                    "TDS": 0.00,
                    "ServiceCharge": 0,
                    "TotalGSTAmount": 1414.1693,
                    "GST": {
                        "CGSTAmount": 0.0000,
                        "CGSTRate": 0,
                        "CessAmount": 0.0000,
                        "CessRate": 0,
                        "IGSTAmount": 1414.1693,
                        "IGSTRate": 18,
                        "SGSTAmount": 0.0000,
                        "SGSTRate": 0,
                        "TaxableAmount": 7856.50
                    }
                },
                "HotelPicture": "https://api.tbotechnology.in/imageresource.aspx?img=9eMP+0FIICgCIk6ZClzZH9Cs+1gwAq6BFWcc22yNLMF/UJIXMdxPdRpAyYgh22RZEzsGxP7kxsYyvbEExt+7unKwC99Cnlbzvr8KAfoY6wg=",
                "HotelAddress": "Humbran Road Ludhiana 141007 , ",
                "HotelContactNo": "",
                "HotelMap": null,
                "Latitude": "",
                "Longitude": "",
                "HotelLocation": null,
                "SupplierPrice": null,
                "RoomDetails": []
            },
        cityName:'Mumbai'},
        ],
       
    
};
