export const CITY_JSON: any[] =

[
  {
    "Continent": "Asia",
    "countries": [      {
      "Country": "Armenia",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa on arrival / eVisa",
      "Cities": [
        "Yerevan",
        "Gyumri",
        "Vanadzor",
        "Sevan",
        "Dilijan",
        "Etchmiadzin",
        "Kapan",
        "Ashtarak",
        "Hrazdan",
        "Abovyan",
        "Sisian",
        "Vayk",
        "Martuni",
        "Chambarak",
        "Ijevan"
      ]
    },
    {
      "Country": "Turkey",
      "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
      "Visa Details": "Schengen Consulate Application",
      "Cities": [
        'Istanbul', 
        'Ankara', 
        'Antalya', 
        'Izmir', 
        'Bursa', 
        'Gaziantep', 
        'Konya', 
        'Adana', 
        'Mersin', 
        'Eskişehir', 
        'Trabzon', 
        'Samsun', 
        'Kayseri', 
        'Erzurum', 
        'Sivas'
      ]
    },
    {
      "Country": "Azerbaijan",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa on arrival / eVisa",
      "Cities": [
        "Baku",
        "Ganja",
        "Sumqayit",
        "Sheki",
        "Quba",
        "Lankaran",
        "Mingachevir",
        "Naxçivan",
        "Barda",
        "Zaqatala",
        "Shaki",
        "Gabala",
        "Qusar",
        "Masally",
        "Hajigabul"
      ]
    },
    {
      "Country": "Bahrain",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "eVisa / Visa on arrival / Visa-free",
      "Cities": [
        "Manama",
        "Muharraq",
        "Riffa",
        "A'ali",
        "Madinat Hamad",
        "Isa Town",
        "Sitra",
        "Budaiya",
        "Al Muharraq",
        "Al Da'asa",
        "Al Riffa",
        "Al Hidd",
        "Al Budayyi'",
        "Al Khaleej",
        "Al Jasra"
      ]
    },
    {
      "Country": "Bangladesh",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa required (Tourist visa)",
      "Cities": [
        "Dhaka",
        "Chittagong",
        "Khulna",
        "Sylhet",
        "Rajshahi",
        "Barisal",
        "Rangpur",
        "Narayanganj",
        "Comilla",
        "Mymensingh",
        "Bogra",
        "Pabna",
        "Jessore",
        "Jhenaidah",
        "Faridpur"
      ]
    },
    {
      "Country": "Bhutan",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa required (Tourist visa)",
      "Cities": [
        "Thimphu",
        "Paro",
        "Punakha",
        "Wangdue Phodrang",
        "Thimphu (Wangchhu)",
        "Bumthang",
        "Gasa",
        "Trongsa",
        "Mongar",
        "Trashigang",
        "Tashi Yangtse",
        "Lhuentse",
        "Samtse",
        "Zhemgang",
        "Pemagatshel"
      ]
    },
    {
      "Country": "Brunei",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa on arrival",
      "Cities": [
        "Bandar Seri Begawan",
        "Muara",
        "Tutong",
        "Seria",
        "Kuala Belait",
        "Bangar",
        "Temburong",
        "Kampong Ayer",
        "Labu",
        "Lumut",
        "Telisai",
        "Seria (Kuala Belait)",
        "Tutong (Kuala Belait)",
        "Kuala Lurah",
        "Sungai Liang"
      ]
    },
    {
      "Country": "Cambodia",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa on arrival / eVisa",
      "Cities": [
        "Siem Reap",
        "Phnom Penh",
        "Sihanoukville",
        "Battambang",
        "Siem Reap (Angkor)",
        "Kampot",
        "Kep",
        "Pailin",
        "Sihanoukville (Kampot)",
        "Kampong Cham",
        "Kratie",
        "Pursat",
        "Takeo",
        "Svay Rieng",
        "Koh Kong"
      ]
    },
    {
      "Country": "China",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa required (Tourist visa)",
      "Cities": [
        "Beijing",
        "Shanghai",
        "Guangzhou",
        "Shenzhen",
        "Chongqing",
        "Tianjin",
        "Chengdu",
        "Hangzhou",
        "Xi'an",
        "Harbin",
        "Nanjing",
        "Qingdao",
        "Changsha",
        "Shenyang",
        "Yangshuo"
      ]
    },
    {
      "Country": "Georgia",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "Visa on arrival / eVisa",
      "Cities": [
        "Tbilisi",
        "Batumi",
        "Kutaisi",
        "Zugdidi",
        "Gori",
        "Rustavi",
        "Akhaltsikhe",
        "Mtskheta",
        "Borjomi",
        "Telavi",
        "Ambrolauri",
        "Kutaisi (Gelati)",
        "Sighnaghi",
        "Kazbegi",
        "Mestia"
      ]
    },
    {
      "Country": "India",
      "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
      "Visa Details": "eVisa / Visa on arrival",
      "Cities": [
        "New Delhi",
        "Mumbai",
        "Chennai",
        "Kolkata",
        "Bangalore",
        "Hyderabad",
        "Ahmedabad",
        "Pune",
        "Jaipur",
        "Varanasi",
        "Goa",
        "Mysore",
        "Indore",
        "Jaisalmer",
        "Kochi"
      ]
    },
      {
        "Country": "Indonesia",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Visa on arrival, eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Jakarta",
          "Bali",
          "Surabaya",
          "Medan",
          "Bandung",
          "Semarang",
          "Yogyakarta",
          "Surakarta (Solo)",
          "Denpasar",
          "Palembang",
          "Makassar",
          "Samarinda",
          "Lake Toba",
          "Borobudur",
          "Lombok"
        ]
      },
      {
        "Country": "Israel",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Consulate application, eVisa, Visa on arrival (for some purposes)",
        "Cities": [
          "Jerusalem",
          "Tel Aviv",
          "Haifa",
          "Eilat",
          "Tiberias",
          "Safed",
          "Nazareth",
          "Ashdod",
          "Beersheba",
          "Rishon LeZion",
          "Netanya",
          "Ashkelon",
          "Petah Tikva",
          "Bnei Brak",
          "Holon"
        ]
      },
      {
        "Country": "Japan",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Consulate application, Visa on arrival (for some purposes)",
        "Cities": [
          "Tokyo",
          "Kyoto",
          "Osaka",
          "Yokohama",
          "Kamakura",
          "Nara",
          "Hiroshima",
          "Nagasaki",
          "Sapporo",
          "Fukuoka",
          "Kobe",
          "Sendai",
          "Nara",
          "Sapporo",
          "Hakone"
        ]
      },
      {
        "Country": "Kazakhstan",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Consulate application",
        "Cities": [
          "Nur-Sultan",
          "Almaty",
          "Shymkent",
          "Astana",
          "Aktobe",
          "Karaganda",
          "Kostanay",
          "Pavlodar",
          "Öskemen",
          "Taraz",
          "Semey",
          "Uralsk",
          "Petropavlovsk",
          "Taldykorgan",
          "Kyzylorda"
        ]
      },
      {
        "Country": "Kyrgyzstan",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Bishkek",
          "Osh",
          "Karakol",
          "Jalalabad",
          "Naryn",
          "Talas",
          "Toktogul",
          "Kara-Suu",
          "Batken",
          "Issyk-Kul",
          "Cholpon-Ata",
          "Karakol (Issyk-Kul)",
          "Balykchy",
          "Son-Kul",
          "Tyup"
        ]
      },
      {
        "Country": "Laos",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Visa on arrival, eVisa",
        "Cities": [
          "Luang Prabang",
          "Vientiane",
          "Vang Vieng",
          "Luang Namtha",
          "Pakse",
          "Savannakhet",
          "Thakhek",
          "Nong Khai",
          "Pakse (Champasak)",
          "Huay Xai",
          "Luang Namtha (Luang Prabang)",
          "Attapeu",
          "Salavan",
          "Champasak",
        ]
      },
      {
        "Country": "Lebanon",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Visa on arrival, eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Beirut",
          "Tyre",
          "Sidon",
          "Tripoli",
          "Baalbek",
          "Byblos",
          "Jounieh",
          "Zahle",
          "Akkar",
          "Hermel",
          "Qamishli",
          "Tartous",
          "Tripoli (Lebanon)",
          "Sour",
          "Nabatieh"
        ]
      },
      {
        "Country": "Malaysia",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Kuala Lumpur",
          "George Town",
          "Malacca",
          "Johor Bahru",
          "Ipoh",
          "Kuching",
          "Kota Kinabalu",
          "Penang",
          "Kuantan",
          "Petaling Jaya",
          "Malacca (Melaka)",
          "Shah Alam",
          "Seremban",
          "Cyberjaya",
          "Miri"
        ]
      },
      {
        "Country": "Philippines",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Visa on arrival, eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Manila",
          "Cebu",
          "Davao",
          "Angeles",
          "Bacolod",
          "Iloilo City",
          "Puerto Princesa",
          "Zamboanga City",
          "Cagayan de Oro City",
          "Davao del Sur",
          "General Santos City",
          "Tacloban City",
          "Bacolod City",
          "Dumaguete City",
          "Cotabato City"
        ]
      },
      {
        "Country": "Singapore",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Singapore",
          "Johor Bahru",
          "Malacca",
          "Penang",
          "George Town",
          "Ipoh",
          "Kuala Lumpur",
          "Petaling Jaya",
          "Klang",
          "Seremban",
        ]
      },
      {
        "Country": "South Korea",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Seoul",
          "Busan",
          "Jeju",
          "Daegu",
          "Gwangju",
          "Incheon",
          "Daejeon",
          "Ulsan",
          "Suwon",
          "Changwon",
          "Sejong",
          "Goyang",
          "Chuncheon",
          "Anyang",
          "Cheonan"
        ]
      },
      {
        "Country": "Thailand",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Visa on arrival, eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Bangkok",
          "Phuket",
          "Chiang Mai",
          "Pattaya",
          "Surat Thani",
          "Hat Yai",
          "Hua Hin",
          "Nakhon Si Thammarat",
          "Udon Thani",
          "Khon Kaen",
          "Krabi",
          "Phuket (Thailand)",
          "Chiang Mai (Thailand)",
          "Pattaya (Thailand)"
        ]
      },
      {
        "Country": "United Arab Emirates",
        "Recommended Months": ['September', 'October', 'November', 'December', 'January', 'February', 'March', 'April'],
        "Visa Details": "Visa on arrival, eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Dubai",
          "Abu Dhabi",
          "Sharjah",
          "Ajman",
          "Ras Al Khaimah",
          "Fujairah",
          "Umm Al Quwain",
          "Al Ain",
          "Al Dhafra",
          "Umm Al Quwain (United Arab Emirates)",
          "Ras Al Khaimah (United Arab Emirates)",
          "Fujairah (United Arab Emirates)",
          "Al Ain (United Arab Emirates)",
          "Al Dhafra (United Arab Emirates)",
          "Ajman (United Arab Emirates)"
        ]
      },
      {
        "Country": "Jordan",
        "Recommended Months": "September - April",
        "Visa Details": "Visa on arrival (Visa waiver)",
        "Cities": [
          "Amman",
          "Petra",
          "Wadi Rum",
          "Madaba",
          "Jerash",
          "Karak",
          "Aqaba",
          "Ajloun",
          "Al Salt",
          "Irbid",
          "Zarqa",
          "Ma'an",
          "Tafileh",
          "Tafila",
          "Umm Qays"
        ]
      },
      {
        "Country": "Kuwait",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Kuwait City",
          "Al Ahmadi",
          "Hawalli",
          "Jahra",
          "Farwaniya",
          "Mubarak Al-Kabeer",
          "Ahmadi",
          "Salmiya",
          "Mangaf",
          "Wafra",
          "Abdali",
          "Jahra (Kuwait City)",
          "Doha (Kuwait City)",
          "Mishrif",
          "Riqqa"
        ]
      },
      {
        "Country": "Maldives",
        "Recommended Months": "September - April",
        "Visa Details": "Visa on arrival",
        "Cities": [
          "Male",
          "Hulhumale",
          "Addu City",
          "Fuvahmulah",
          "Thinadhoo",
          "Kudahuvadhoo",
          "Naifaru",
          "Madivaru",
          "Gan",
          "Villingili",
          "Male (Kaafu)",
          "Mahibadhoo",
          "Thulusdhoo",
          "Meedhoo",
          "Ukulhas"
        ]
      },
      {
        "Country": "Mongolia",
        "Recommended Months": "September - April",
        "Visa Details": "Visa on arrival",
        "Cities": [
          "Ulaanbaatar",
          "Erdenet",
          "Moron",
          "Karakorum",
          "Khovd",
          "Darkhan",
          "Bulgan",
          "Ulaanbaatar (Selenge)",
          "Khentii",
          "Sukhbaatar",
          "Orkhon",
          "Darhan (Orkhon)",
          "Ondorkhaan",
          "Sainshand",
          "Dzud-Durgun"
        ]
      },
      {
        "Country": "Myanmar (Burma)",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Yangon",
          "Mandalay",
          "Nay Pyi Taw",
          "Bagan",
          "Inle Lake",
          "Hpaung Daw U",
          "Kalaw",
          "Mawlamyine",
          "Dawei",
          "Myeik",
          "Taungoo",
          "Monywa",
          "Kengtung",
          "Lashio",
          "Hsipaw"
        ]
      },
      {
        "Country": "Nepal",
        "Recommended Months": "September - April",
        "Visa Details": "Visa on arrival",
        "Cities": [
          "Kathmandu",
          "Pokhara",
          "Lumbini",
          "Patan",
          "Bhaktapur",
          "Nagarkot",
          "Chitwan National Park",
          "Gorkha",
          "Bandipur",
          "Lumbini (Rupandehi)",
          "Mustang",
          "Dolpo",
          "Manang",
          "Mustang (Mustang)",
          "Dolpo (Dolpo)"
        ]
      },
      {
        "Country": "North Korea",
        "Recommended Months": "September - April",
        "Visa Details": "Visa required (Tourist visa)",
        "Cities": [
          "Pyongyang",
          "Wonsan",
          "Kaesong",
          "Hamhung",
          "Chongjin",
          "Nampo",
          "Sariwon",
          "Sinuiju",
          "Chongjin",
          "Hyesan",
          "Rason",
          "Anju",
          "Tokchon",
          "Pyongsong",
          "Kaechon"
        ]
      },
      {
        "Country": "Oman",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa",
        "Cities": [
          "Muscat",
          "Salalah",
          "Nizwa",
          "Sur",
          "Rustaq",
          "Sohar",
          "Barka",
          "Ibra",
          "Jebel Akhdar",
          "Quriyat",
          "Bidbid",
          "Al Hamra",
          "Manah",
          "Dima W'attaiyin",
          "Bahla"
        ]
      },
      {
        "Country": "Qatar",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Doha",
          "Al Wakrah",
          "Al Khor",
          "Al Rayyan",
          "Umm Salal",
          "Madinat ash Shamal",
          "Al Khor",
          "Al Daayen",
          "Al Ghariyah",
          "Al Khawr",
          "Mesaimeer",
          "Al Wakrah",
          "Al Sailiya",
          "Al Aziziyah",
        ]
      },
      {
        "Country": "Russia",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa required",
        "Cities": [
          "Moscow",
          "St. Petersburg",
          "Sochi",
          "Yekaterinburg",
          "Nizhny Novgorod",
          "Kazan",
          "Samara",
          "Rostov-on-Don",
          "Ufa",
          "Krasnodar",
          "Vladivostok",
          "Volgograd",
          "Chelyabinsk",
          "Saratov",
          "Voronezh"
        ]
      },
      {
        "Country": "Saudi Arabia",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Riyadh",
          "Jeddah",
          "Mecca",
          "Medina",
          "Dammam",
          "Taif",
          "Khobar",
          "Abha",
          "Tabuk",
          "Yanbu",
          "Jubail",
          "Hail",
          "Buraidah",
          "Qassim",
          "Al-Ahsa"
        ]
      },
      {
        "Country": "Sri Lanka",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Colombo",
          "Kandy",
          "Galle",
          "Jaffna",
          "Negombo",
          "Trincomalee",
          "Matara",
          "Kalutara",
          "Dambulla",
          "Anuradhapura",
          "Polonnaruwa",
          "Kandy (Sri Lanka)",
          "Galle (Sri Lanka)",
          "Jaffna (Sri Lanka)",
        ]
      },
      {
        "Country": "Syria",
        "Recommended Months": "September - April",
        "Visa Details": "Visa required (Tourist visa)",
        "Cities": [
          "Damascus",
          "Aleppo",
          "Latakia",
          "Homs",
          "Hama",
          "Daraa",
          "Tartus",
          "Deir ez-Zor",
          "Al-Hasakah",
          "Raqqa",
          "Idlib",
          "Qamishli",
          "As-Suwayda",
          "Al-Ma'arrat an-Nu'man",
        ]
      },
      {
        "Country": "Taiwan",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Taipei",
          "Kaohsiung",
          "Taichung",
          "Taoyuan",
          "Hsinchu",
          "Keelung",
          "Tainan",
          "Changhua",
          "Chiayi",
          "Taitung",
          "Yilan",
          "Nantou",
          "Hualien",
          "Penghu",
        ]
      },
      {
        "Country": "Tajikistan",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Dushanbe",
          "Khujand",
          "Istaravshan",
          "Kulob",
          "Khorog",
          "Penjikent",
          "Tursunzoda",
          "Panjakent",
          "Nurek",
          "Hissar",
          "Bokhtar",
          "Kurgan-Tyube",
          "Fayzobod",
          "Ayni",
          "Rasht"
        ]
      },
      {
        "Country": "Timor-Leste",
        "Recommended Months": "September - April",
        "Visa Details": "Visa on arrival",
        "Cities": [
          "Dili",
          "Baucau",
          "Liquica",
          "Manatuto",
          "Same",
          "Maliana",
          "Viqueque",
          "Oecusse",
          "Ainaro",
          "Bobonaro",
          "Ermera",
          "Aileu",
          "Manufahi",
          "Lautém",
        ]
      },
      {
        "Country": "Turkmenistan",
        "Recommended Months": "September - April",
        "Visa Details": "Visa required (Tourist visa)",
        "Cities": [
          "Ashgabat",
          "Turkmenabat",
          "Dashoguz",
          "Mary",
          "Türkmenbashi",
          "Balkanabat",
          "Ahal",
          "Lebap",
          "Dashoguz (Turkmenistan)",
          "Balkan (Turkmenistan)",
          "Mary (Turkmenistan)",
          "Ahal (Turkmenistan)",
          "Lebap (Turkmenistan)",
          "Dashoguz (Turkmenistan)",
        ]
      },
      {
        "Country": "Uzbekistan",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa",
        "Cities": [
          "Tashkent",
          "Samarkand",
          "Bukhara",
          "Khiva",
          "Namangan",
          "Fergana",
          "Andijan",
          "Nukus",
          "Termez",
          "Jizzakh",
          "Navoi",
          "Qarshi",
          "Bukhara (Uzbekistan)",
          "Samarkand (Uzbekistan)",
        ]
      },
      {
        "Country": "Vietnam",
        "Recommended Months": "September - April",
        "Visa Details": "eVisa / Visa on arrival",
        "Cities": [
          "Hanoi",
          "Ho Chi Minh City",
          "Da Nang",
          "Haiphong",
          "Hue",
          "Can Tho",
          "Da Lat",
          "Phu Quoc",
          "Vung Tau",
          "Quy Nhon",
          "Hue (Vietnam)",
          "Haiphong (Vietnam)",
          "Can Tho (Vietnam)",
          "Da Lat (Vietnam)",
          "Nha Trang (Vietnam)"
        ]
      },
      {
        "Country": "Yemen",
        "Recommended Months": "September - April",
        "Visa Details": "Visa required (Tourist visa)",
        "Cities": [
          "Sanaa",
          "Aden",
          "Taiz",
          "Hodeidah",
          "Ibb",
          "Sa'dah",
          "Dhamar",
          "Marib",
          "Al Hudaydah",
          "Hajjah",
          "Ta'izz",
          "Amran",
          "Raymah",
          "Al Jawf",
          "Ma'rib (Yemen)"
        ]
      }
    ]
  },
  {
    "Continent": "Europe",
    "countries": [
      {
        "Country": "Albania",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Visa Types":"Visa on arrival / eVisa",
        "Cities": [
          "Tirana",
          "Durrës",
          "Shkodra",
          "Berat",
          "Kruja",
          "Vlorë",
          "Gjirokastër",
          "Saranda",
          "Dajti",
          "Pogradec",
          "Shkodër",
          "Korçë",
          "Elbasan",
          "Kukës"
        ]
      },
      {
        "Country": "Andorra",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Andorra la Vella",
          "Escaldes-Engordany",
          "La Massana",
          "Sant Julià de Lòria",
          "Pas de la Casa",
          "Encamp",
          "Canillo",
          "Ordino",
          "Arinsal",
          "Pal",
          "Sant Moritz",
          "Davos",
          "Chur",
          "Scuol",
          "Zermatt"
        ]
      },
      {
        "Country": "Austria",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Vienna",
          "Salzburg",
          "Innsbruck",
          "Graz",
          "Klagenfurt",
          "Bregenz",
          "Linz",
          "Salzburgerland",
          "Tyrol",
          "Vorarlberg",
          "Hallstatt",
          "Zell am See",
          "Kaprun",
          "Bad Gastein",
          "Eisenstadt"
        ]
      },
      {
        "Country": "Belarus",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Minsk",
          "Brest",
          "Gomel",
          "Vitebsk",
          "Mogilev",
          "Grodno",
          "Polotsk",
          "Slutsk",
          "Neman",
          "Orsha",
          "Pinsk",
          "Lida",
          "Kobrin",
          "Vitebsk",
          "Novopolotsk"
        ]
      },
      {
        "Country": "Belgium",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Brussels",
          "Antwerp",
          "Bruges",
          "Ghent",
          "Liège",
          "Namur",
          "Charleroi",
          "Mons",
          "Tournai",
          "Ostend",
          "Mechelen",
          "Leuven",
          "Hasselt",
          "Aalst",
          "Genk"
        ]
      },
      {
        "Country": "Bosnia and Herzegovina",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Sarajevo",
          "Mostar",
          "Banja Luka",
          "Tuzla",
          "Zenica",
          "Goražde",
          "Travnik",
          "Bihać",
          "Bijeljina",
          "Zvornik",
          "Jajce",
          "Zenica",
          "Konjic",
          "Foča",
          "Goražde"
        ]
      },
      {
        "Country": "Bulgaria",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Sofia",
          "Plovdiv",
          "Varna",
          "Burgas",
          "Ruse",
          "Stara Zagora",
          "Pleven",
          "Shumen",
          "Dobrich",
          "Gabrovo",
          "Veliko Tarnovo",
          "Lovech",
          "Pernik",
          "Haskovo",
          "Sliven"
        ]
      },
      {
        "Country": "Croatia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Zagreb",
          "Split",
          "Dubrovnik",
          "Zadar",
          "Rijeka",
          "Osijek",
          "Pula",
          "Šibenik",
          "Zadar",
          "Varaždin",
          "Slavonski Brod",
          "Sisak",
          "Koprivnica",
          "Karlovac",
          "Gospić"
        ]
      },
      {
        "Country": "Cyprus",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Nicosia",
          "Limassol",
          "Larnaca",
          "Paphos",
          "Kyrenia",
          "Famagusta",
          "Ayia Napa",
          "Protaras",
          "Limni",
          "Polis Chrysochous",
          "Latchi",
          "Troodos",
          "Paphos",
          "Polis Chrysochous"
        ]
      },
      {
        "Country": "Czech Republic",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Prague",
          "Brno",
          "Ostrava",
          "Plzeň",
          "Liberec",
          "Olomouc",
          "Hradec Králové",
          "České Budějovice",
          "Zlín",
          "Jihlava",
          "Karlovy Vary",
          "Ústí nad Labem",
          "Pardubice",
          "Kladno",
          "Teplice"
        ]
      },
      {
        "Country": "Denmark",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Copenhagen",
          "Århus",
          "Odense",
          "Aalborg",
          "Esbjerg",
          "Randers",
          "Horsens",
          "Kolding",
          "Frederiksberg",
          "Roskilde",
          "Vejle",
          "Herning",
          "Silkeborg",
          "Helsingør",
          "Næstved"
        ]
      },
      {
        "Country": "Estonia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Tallinn",
          "Tartu",
          "Narva",
          "Pärnu",
          "Kohtla-Järve",
          "Viljandi",
          "Rakvere",
          "Jõhvi",
          "Kuressaare",
          "Haapsalu",
          "Paide",
          "Valga",
          "Võru",
          "Tapa",
          "Sillamäe"
        ]
      },
      {
        "Country": "Finland",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Helsinki",
          "Tampere",
          "Turku",
          "Espoo",
          "Vantaa",
          "Oulu",
          "Lahti",
          "Tampere",
          "Jyväskylä",
          "Kuopio",
          "Pori",
          "Lappeenranta",
          "Kotka",
          "Mikkeli",
          "Joensuu"
        ]
      },
      {
        "Country": "France",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Paris",
          "Marseille",
          "Lyon",
          "Nice",
          "Toulouse",
          "Bordeaux",
          "Nantes",
          "Strasbourg",
          "Montpellier",
          "Lille",
          "Rennes",
          "Reims",
          "Le Havre",
          "Saint-Étienne",
          "Grenoble"
        ]
      },
      {
        "Country": "Germany",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Berlin",
          "Munich",
          "Frankfurt am Main",
          "Hamburg",
          "Cologne",
          "Stuttgart",
          "Düsseldorf",
          "Dortmund",
          "Essen",
          "Leipzig",
          "Bremen",
          "Dresden",
          "Hannover",
          "Nürnberg",
          "Duisburg"
        ]
      },
      {
        "Country": "Greece",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Athens",
          "Thessaloniki",
          "Patras",
          "Heraklion",
          "Nafplio",
          "Santorini",
          "Mykonos",
          "Chania",
          "Kalamata",
          "Rhodes",
          "Kavala",
          "Piraeus",
          "Corfu",
          "Agrinio",
          "Preveza"
        ]
      },
      {
        "Country": "Hungary",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Budapest",
          "Debrecen",
          "Miskolc",
          "Szeged",
          "Pécs",
          "Tihany",
          "Nyíregyháza",
          "Székesfehérvár",
          "Kecskemét",
          "Zalaegerszeg",
          "Veszprém",
          "Eger",
          "Szombathely",
          "Nagykanizsa",
          "Szolnok"
        ]
      },
      {
        "Country": "Iceland",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Reykjavík",
          "Akureyri",
          "Selfoss",
          "Hafnarfjörður",
          "Garðabær",
          "Keflavík"
        ]
      },
      {
        "Country": "Ireland",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Dublin",
          "Cork",
          "Galway",
          "Limerick",
          "Waterford",
          "Sligo",
          "Drogheda",
          "Dundalk",
          "Navan",
          "Longford",
          "Carlow",
          "Kilkenny",
          "Wexford",
          "Wicklow",
          "Kerry"
        ]
      },
      {
        "Country": "Italy",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Rome",
          "Milan",
          "Naples",
          "Florence",
          "Venice",
          "Turin",
          "Palermo",
          "Bologna",
          "Genoa",
          "Cinque Terre",
          "Tuscany",
          "Pompeii",
          "Sorrento",
          "Amalfi Coast",
          "Pisa"
        ]
      },
      {
        "Country": "Kosovo",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Pristina",
          "Prizren",
          "Peja",
          "Gjilan",
          "Ferizaj",
          "Mitrovica",
          "Vushtrri",
          "Skenderaj",
          "Gjakovë",
          "Fushë Kosova",
          "Obiliq",
          "Klinë",
          "Deçan",
          "Malishevë",
          "Rahovec"
        ]
      },
      {
        "Country": "Latvia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Riga",
          "Daugavpils",
          "Liepāja",
          "Jūrmala",
          "Valmiera",
          "Ventspils",
          "Rēzekne",
          "Jelgava",
          "Jēkabpils",
          "Aizkraukle",
          "Ogre",
          "Sigulda",
          "Cēsis",
          "Kuldīga",
          "Talsi"
        ]
      },
      {
        "Country": "Liechtenstein",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Vaduz",
          "Schaan",
          "Triesen",
          "Balzers",
          "Triesenberg",
          "Eschen",
          "Mauren",
          "Triesen",
          "Ruggell",
          "Gamprin",
          "Nendeln",
          "Schellenberg",
          "Planken",
          "Triesenberg",
          "Malbun"
        ]
      },
      {
        "Country": "Lithuania",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Vilnius",
          "Kaunas",
          "Klaipėda",
          "Šiauliai",
          "Panevėžys",
          "Alytus",
          "Marijampolė",
          "Tauragė",
          "Telšiai",
          "Utena",
          "Kėdainiai",
          "Jonava",
          "Ukmergė",
          "Raseiniai",
          "Radviliškis"
        ]
      },
      {
        "Country": "Luxembourg",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Luxembourg City",
          "Esch-sur-Alzette",
          "Differdange",
          "Dudelange",
          "Wiltz",
          "Ettelbruck",
          "Diekirch",
          "Vianden",
          "Clervaux",
          "Remich",
          "Echternach",
          "Mondorf-les-Bains",
          "Pétange",
          "Differdange",
          "Mamer"
        ]
      },
      {
        "Country": "North Macedonia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Skopje",
          "Bitola",
          "Prilep",
          "Tetovo",
          "Kumanovo",
          "Ohrid",
          "Štip",
          "Gostivar",
          "Veles",
          "Strumica",
          "Kočani",
          "Kavadarci",
          "Negotino",
          "Delčevo",
          "Gevgelija"
        ]
      },
      {
        "Country": "Malta",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Valletta",
          "Birgu",
          "Sliema",
          "St. Julian's",
          "Qormi",
          "Mdina",
          "Mosta",
          "Marsaxlokk",
          "Rabat",
          "Naxxar",
          "Għarb",
          "Mellieħa",
          "Żebbuġ",
          "Gozo",
          "Tarxien"
        ]
      },
      {
        "Country": "Moldova",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Chișinău",
          "Tiraspol",
          "Bălți",
          "Bender",
          "Ungheni",
          "Cahul",
          "Comrat",
          "Drochia",
          "Strășeni",
          "Orhei",
          "Edineț",
          "Soroca",
          "Rezina",
          "Taraclia",
          "Leova"
        ]
      },
      {
        "Country": "Monaco",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Monaco",
          "Monte Carlo",
          "Fontvieille",
          "La Condamine",
          "La Turbie",
          "Roquebrune-Cap-Martin",
          "Cap-d'Ail",
          "Èze",
          "Beausoleil",
          "Menton"
        ]
      },
      {
        "Country": "Montenegro",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Podgorica",
          "Nikšić",
          "Budva",
          "Kotor",
          "Bar",
          "Ulcinj",
          "Tivat",
          "Herceg Novi",
          "Cetinje",
          "Berane",
          "Žabljak",
          "Pljevlja",
          "Bijelo Polje"
        ]
      },
      {
        "Country": "Netherlands",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Amsterdam",
          "Rotterdam",
          "The Hague",
          "Utrecht",
          "Eindhoven",
          "Groningen",
          "Almere",
          "Breda",
          "Nijmegen",
          "Enschede",
          "Haarlem",
          "Zwolle",
          "Maastricht",
          "Apeldoorn",
          "Tilburg"
        ]
      },
      {
        "Country": "Norway",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Oslo",
          "Bergen",
          "Trondheim",
          "Stavanger",
          "Tromsø",
          "Kristiansand",
          "Drammen",
          "Fredrikstad",
          "Sandnes",
          "Skien",
          "Notodden",
          "Haugesund",
          "Lillehammer",
          "Sarpsborg",
          "Halden"
        ]
      },
      {
        "Country": "Poland",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Warsaw",
          "Kraków",
          "Gdańsk",
          "Wrocław",
          "Łódź",
          "Poznań",
          "Szczecin",
          "Lublin",
          "Katowice",
          "Białystok",
          "Rzeszów",
          "Bytom",
          "Toruń",
          "Zabrze",
          "Kielce"
        ]
      },
      {
        "Country": "Portugal",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Lisbon",
          "Porto",
          "Faro",
          "Albufeira",
          "Funchal",
          "Évora",
          "Coimbra",
          "Braga",
          "Setúbal",
          "Guimarães",
          "Aveiro",
          "Nazaré",
          "Portimão",
          "Vila Nova de Gaia",
          "Sines"
        ]
      },
      {
        "Country": "Romania",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Bucharest",
          "Cluj-Napoca",
          "Timișoara",
          "Iași",
          "Constanța",
          "Craiova",
          "Brașov",
          "Galați",
          "Ploiești",
          "Brăila",
          "Oradea",
          "Sibiu",
          "Bacău",
          "Arad",
          "Pitești"
        ]
      },
      {
        "Country": "Russia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Moscow",
          "Saint Petersburg",
          "Sochi",
          "Kazan",
          "Nizhny Novgorod",
          "Yekaterinburg",
          "Samara",
          "Rostov-on-Don",
          "Volgograd",
          "Ufa",
          "Chelyabinsk",
          "Krasnodar",
          "Perm",
          "Voronezh",
          "Saratov"
        ]
      },
      {
        "Country": "San Marino",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "San Marino",
          "Borgo Maggiore",
          "Serravalle",
          "Domagnano",
          "Fiorentino",
          "Acquaviva",
          "Faetano",
          "Chiesanuova",
          "Montegiardino",
          "Verucchio"
        ]
      },
      {
        "Country": "Serbia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Belgrade",
          "Novi Sad",
          "Niš",
          "Kragujevac",
          "Subotica",
          "Čačak",
          "Kragujevac",
          "Zrenjanin",
          "Leskovac",
          "Užice",
          "Pančevo",
          "Valjevo",
          "Smederevo",
          "Vranje",
          "Šabac"
        ]
      },
      {
        "Country": "Slovakia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Bratislava",
          "Košice",
          "Prešov",
          "Žilina",
          "Banská Bystrica",
          "Trnava",
          "Nitra",
          "Poprad",
          "Martin",
          "Trenčín",
          "Prievidza",
          "Žiar nad Hronom",
          "Nové Zámky",
          "Michalovce",
          "Galanta"
        ]
      },
      {
        "Country": "Slovenia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Ljubljana",
          "Maribor",
          "Celje",
          "Kranj",
          "Koper",
          "Novo Mesto",
          "Velenje",
          "Ptuj",
          "Nova Gorica",
          "Jesenice",
          "Krško",
          "Murska Sobota",
          "Škofja Loka",
          "Ilirska Bistrica",
          "Trbovlje"
        ]
      },
      {
        "Country": "Spain",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Madrid",
          "Barcelona",
          "Valencia",
          "Seville",
          "Zaragoza",
          "Málaga",
          "Bilbao",
          "Las Palmas de Gran Canaria",
          "Alicante",
          "Córdoba",
          "Murcia",
          "Valladolid",
          "Vigo",
          "Gijón",
          "Santander"
        ]
      },
      {
        "Country": "Sweden",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Stockholm",
          "Gothenburg",
          "Malmö",
          "Uppsala",
          "Västerås",
          "Örebro",
          "Linköping",
          "Norrköping",
          "Helsingborg",
          "Jönköping",
          "Eskilstuna",
          "Halmstad",
          "Sundsvall",
          "Umeå",
          "Borås"
        ]
      },
      {
        "Country": "Switzerland",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Schengen Consulate Application",
        "Cities": [
          "Zürich",
          "Geneva",
          "Basel",
          "Bern",
          "Lausanne",
          "Winterthur",
          "Lucerne",
          "St. Gallen",
          "Fribourg",
          "Neuchâtel",
          "Grindelwald",
          "Lugano",
          "Interlaken",
          "Zermatt",
          "St. Moritz"
        ]
      }
    ]
  },
  {
    "Continent": "Africa",
    "countries": [
      {
        "Country": "Algeria",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Oran",
          "Constantine",
          "Annaba",
          "Batna",
          "Sétif",
          "Blida",
          "Tlemcen",
          "Mostaganem",
          "Sidi Bel Abbès",
          "Skikda",
          "Chlef",
          "El Oued",
          "Tiaret",
          "Ghardaïa"
        ]
      },
      {
        "Country": "Angola",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Huambo",
          "Benguela",
          "Lubango",
          "Namibe",
          "Saurimo",
          "Malanje",
          "Uíge",
          "Cabinda",
          "Moxico",
          "Cuando Cubango",
          "Kwanza Sul",
          "Bié",
          "Lunda Norte",
          "Lunda Sul",
        ]
      },
      {
        "Country": "Botswana",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / Consulate application (for some purposes)",
        "Cities": [
          "Francistown",
          "Maun",
          "Molepolole",
          "Selibe Phikwe",
          "Kanye",
          "Jwaneng",
          "Orapa",
          "Palapye",
          "Mahalapye",
          "Ghanzi",
          "Selebi-Phikwe",
          "Letlhakane",
          "Tsabong",
          "Ramotswa",
        ]
      },
      {
        "Country": "Burundi",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Gitega",
          "Ngozi",
          "Rumonge",
          "Kayanza",
          "Muramvya",
          "Bukavu",
          "Rutana",
          "Cibitoke",
          "Karuzi",
          "Bururi",
          "Mwaro",
          "Rumonge",
          "Cankuzo",
          "Gihanga",
        ]
      },
      {
        "Country": "Cameroon",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Douala",
          "Garoua",
          "Bamenda",
          "Nkongsamba",
          "Limbe",
          "Buea",
          "Maroua",
          "Bafoussam",
          "Ngaoundéré",
          "Kumba",
          "Bertoua",
          "Ebolowa",
          "Foumban",
          "Kribi",
        ]
      },
      {
        "Country": "Central African Republic",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Berberati",
          "Bouar",
          "Bossangoa",
          "Sibut",
          "Kaga-Bandoro",
          "Mbaïki",
          "Nola",
          "Alindao",
          "Bambari",
          "Paoua",
          "Carnot",
          "Grimari",
          "Birao",
          "Zemio",
        ]
      },
      {
        "Country": "Chad",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Moundou",
          "Sarh",
          "Abéché",
          "Faya-Largeau",
          "Doba",
          "Mongo",
          "Bongor",
          "Kélo",
          "Mao",
          "Am Timan",
          "Léré",
          "Ati",
          "Oum Hadjer",
          "Salal",
        ]
      },
      {
        "Country": "Democratic Republic of the Congo",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Lubumbashi",
          "Mbuji-Mayi",
          "Kananga",
          "Kisangani",
          "Bukavu",
          "Kolwezi",
          "Goma",
          "Matadi",
          "Kikwit",
          "Bunia",
          "Mbandaka",
          "Kindu",
          "Uvira",
          "Kalemie",
        ]
      },
      {
        "Country": "Egypt",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Alexandria",
          "Giza",
          "Luxor",
          "Aswan",
          "El-Mansura",
          "Port Said",
          "Suez",
          "Ismailia",
          "Tanta",
          "Sharm El Sheikh",
          "Dahab",
          "Qena",
          "Sohag",
          "Minya",
        ]
      },
      {
        "Country": "Equatorial Guinea",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Bata",
          "Ebebiyín",
          "Mongomo",
          "Luba",
          "Oyala",
          "Aconibe",
          "Riaba",
          "Mbini",
          "Ebebiyin",
          "Kogo",
          "Evinayong",
          "Niefang",
          "Sipopo",
          "Nsok",
        ]
      },
      {
        "Country": "Eritrea",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Massawa",
          "Keren",
          "Dekemhare",
          "Barentu",
          "Mendefera",
          "Adi Keyh"
        ]
      },
      {
        "Country": "Gambia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Serekunda",
          "Brikama",
          "Bakau",
          "Farafenni",
          "Mansa Konko",
          "Kombo Saint Mary",
          "Kuntaur",
          "Jarra Soma",
          "Gunjur",
          "Basse Santa Su",
          "Janjanbureh",
          "Soma",
          "Niani",
        ]
      },
      {
        "Country": "Ghana",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Kumasi",
          "Takoradi",
          "Tamale",
          "Sunyani",
          "Koforidua",
          "Cape Coast",
          "Sekondi-Takoradi",
          "Obuasi",
          "Wa",
          "Tarkwa",
          "Agona Swedru",
          "Elmina",
          "Nkawkaw",
          "Ho",        ]
      },
      {
        "Country": "Guinea",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Kankan",
          "Kindia",
          "N'Zérékoré",
          "Labé",
          "Mamou",
          "Faranah",
          "Siguiri",
          "Kouroussa",
          "Pita",
          "Gaoual",
          "Boffa",
          "Dalaba",
          "Dabola",
          "Yomou",        ]
      },
      {
        "Country": "Liberia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Gbarnga",
          "Buchanan",
          "Kakata",
          "Zwedru",
          "Ganta",
          "Harper",
          "Tubmanburg",
          "Greenville",
          "Robertsport",
          "Sinkor",
          "Bopolu",
          "Sanniquellie",
          "Karnplay",
          "Sasstown",        ]
      },
      {
        "Country": "Libya",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Benghazi",
          "Misrata",
          "Sebha",
          "Al Bayda",
          "Derna",
          "Tobruk",
          "Ghadames",
          "Sabha",
          "Ajdabiya",
          "Al Khums",
          "Zawiya",
          "Misrata",
          "Ubari",
          "Zuwarah",        ]
      },
      {
        "Country": "Mauritius",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Curepipe",
          "Quatre Bornes",
          "Mahébourg",
          "Grand Port",
          "Rose-Hill",
          "Vacoas-Phoenix",
          "Rodrigues",
          "Flic-en-Flac",
          "Goodlands",
          "Triolet",
          "Beau Bassin-Rose Hill",
          "Tamarin",
          "Le Morne"
        ]
      },
      {
        "Country": "Morocco",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Rabat",
          "Fez",
          "Meknes"
        ]
      },
      {
        "Country": "Niger",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Zinder",
          "Maradi",
          "Agadez",
          "Tahoua",
          "Dosso",
          "Tillabéri",
          "Gouré",
          "Birni N'Konni",
          "Arlit",
          "Diffa",
          "N'Guigmi",
          "Maine-Soroa",
          "Abala",
          "Filingué",
        ]
      },
      {
        "Country": "Nigeria",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Abuja",
          "Kano",
          "Ibadan",
          "Port Harcourt",
          "Kaduna",
          "Benin City",
          "Maiduguri",
          "Enugu",
          "Aba",
          "Ilorin",
          "Jos",
          "Warri",
          "Abeokuta",
          "Oyo",
        ]
      },
      {
        "Country": "Republic of the Congo",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Pointe-Noire",
          "Dolisie",
          "Nkayi",
          "Ouesso",
          "Gamboma",
          "Madingou",
          "Ntoumpa",
          "Lekana",
          "Djambala",
          "Sibiti",
          "Impfondo",
          "Ewo",
          "Ouesso",
          "Makoua",
        ]
      },
      {
        "Country": "Seychelles",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Mahé",
          "Praslin",
          "La Digue",
          "Silhouette",
          "Curieuse",
          "Cousine",
          "Farquhar",
          "Aldabra",
          "Aride",
          "Denis",
          "Alphonse",
          "Desroches",
          "Bird",
          "Frégate",
        ]
      },
      {
        "Country": "Sierra Leone",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Bo",
          "Kenema",
          "Makeni",
          "Lunsar",
          "Port Loko",
          "Magburaka",
          "Kambia",
          "Koidu",
          "Segbwema",
          "Waterloo",
          "Kabala",
          "Moyamba",
          "Bonthe",
          "Yengema",
        ]
      },
      {
        "Country": "South Africa",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa not required for certain purposes (Visa on arrival for some countries)",
        "Cities": [
          "Cape Town",
          "Durban",
          "Pretoria",
          "Soweto",
          "Port Elizabeth",
          "Bloemfontein",
          "East London",
          "Pietermaritzburg",
          "Nelspruit",
          "Rustenburg",
          "Kimberley",
          "Polokwane",
          "Secunda",
          "Mbombela",
        ]
      },
      {
        "Country": "South Sudan",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Wau",
          "Malakal",
          "Bor",
          "Rumbek",
          "Yei",
          "Bentiu",
          "Torit",
          "Kapoeta",
          "Aweil",
          "Nimule",
          "Malakal",
          "Bunj",
          "Nasir",
          "Maridi",
        ]
      },
      {
        "Country": "Sudan",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Omdurman",
          "Port Sudan",
          "El-Fasher",
          "Wadi Halfa",
          "Atbara",
          "Nyala",
          "Kassala",
          "El Obeid",
          "El Daein",
          "Dongola",
          "Kosti",
          "Gedaref",
          "Shendi",
          "Port Sudan",
        ]
      },
      {
        "Country": "Swaziland",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa required (Consulate application)",
        "Cities": [
          "Manzini",
          "Nhlangano",
          "Big Bend",
          "Piggs Peak",
          "Siteki",
          "Lavumisa",
          "Matsapha",
          "Mankayane",
          "Bulembu",
          "Malkerns",
          "Nhlangwini",
          "Hhohho",
          "Matsamo",
          "Mhlume",
        ]
      },
      {
        "Country": "Tunisia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa / Consulate application (for some purposes)",
        "Cities": [
          "Sousse",
          "Sfax",
          "Kairouan",
          "Bizerte",
          "Djerba",
          "Zarzis",
          "Tozeur",
          "Mahdia",
          "Monastir",
          "Gabes",
          "El Jem",
          "Tataouine",
          "El Kef",
          "Sidi Bou Said",
        ]
      }
    ]
  },
  {
    "Continent": "North America",
    "countries": [
      {
        "Country": "Canada",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Consulate application, eTA, Visa on arrival (for some purposes)",
        "Cities": [
          "Toronto",
          "Vancouver",
          "Montreal",
          "Calgary",
          "Ottawa",
          "Quebec City",
          "Edmonton",
          "Winnipeg",
          "Hamilton",
          "Victoria",
          "Halifax",
          "Niagara Falls",
          "Thunder Bay",
          "Saskatoon",
          "Windsor"
        ]
      },
      {
        "Country": "United States",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Consulate application, ESTA",
        "Cities": [
          "New York City",
          "Los Angeles",
          "Chicago",
          "Miami",
          "Houston",
          "San Francisco",
          "Philadelphia",
          "Phoenix",
          "San Antonio",
          "Dallas",
          "Seattle",
          "Washington",
          "D.C.",
          "Boston",
          "Atlanta"
        ]
      },
      {
        "Country": "Mexico",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival (Tourist card), Consulate application",
        "Cities": [
          "Mexico City",
          "Cancun",
          "Guadalajara",
          "Monterrey",
          "Puebla",
          "Tijuana",
          "Puerto Vallarta",
          "Mérida",
          "Oaxaca",
          "León",
          "Guanajuato",
          "Morelia",
          "Cuernavaca",
          "Veracruz",
          "San Miguel de Allende"
        ]
      },
      {
        "Country": "Greenland",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa not required for certain purposes",
        "Cities": [
          "Nuuk",
          "Ilulissat",
          "Qaqortoq",
          "Sisimiut",
          "Maniitsoq",
          "Narsarsuaq",
          "Uummannaq",
          "Tasiilaq",
          "Qasigiannguit",
          "Aasiaat",
          "Narsaq"
        ]
      },
      {
        "Country": "Saint Pierre and Miquelon",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa not required for certain purposes",
        "Cities": [
          "Saint-Pierre",
          "Miquelon"
        ]
      },
      {
        "Country": "Antigua and Barbuda",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Saint John's",
          "Codrington"
        ]
      },
      {
        "Country": "Bahamas",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Nassau",
          "Freeport",
          "George Town",
          "Marsh Harbour",
          "Exuma",
          "Eleuthera",
          "Harbour Island",
          "Cat Island",
          "Andros",
          "Long Island",
          "Crooked Island",
          "Acklins Island"
        ]
      },
      {
        "Country": "Barbados",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Bridgetown",
          "Speightstown",
          "Holetown",
          "Oistins"
        ]
      },
      {
        "Country": "Belize",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Belize City",
          "San Ignacio",
          "Placencia",
          "Caye Caulker",
          "Ambergris Caye",
          "Corozal",
          "Punta Gorda",
          "San Pedro",
          "Dangriga",
          "Hopkins"
        ]
      },
      {
        "Country": "Costa Rica",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival, eVisa, Consulate application (for some purposes)",
        "Cities": [
          "San José",
          "Liberia",
          "Puerto Viejo",
          "Tamarindo",
          "Manuel Antonio",
          "Monteverde",
          "La Fortuna",
          "Jaco",
          "Nosara",
          "Quepos",
          "Puerto Jiménez",
          "Tortuguero"
        ]
      },
      {
        "Country": "Cuba",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Tourist card, Visa on arrival",
        "Cities": [
          "Havana",
          "Santiago de Cuba",
          "Varadero",
          "Cienfuegos",
          "Trinidad",
          "Holguín",
          "Camagüey",
          "Cayo Coco",
          "Cayo Largo",
          "Cayo Santa María",
          "Pinar del Río"
        ]
      },
      {
        "Country": "Dominica",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Roseau",
          "Portsmouth",
          "Marigot"
        ]
      },
      {
        "Country": "Dominican Republic",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Santo Domingo",
          "Punta Cana",
          "Puerto Plata",
          "La Romana",
          "Samaná",
          "Bayahibe",
          "Barahona",
          "Santiago",
          "Sosúa",
          "Cabarete"
        ]
      },
      {
        "Country": "El Salvador",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "San Salvador",
          "Santa Ana",
          "San Miguel",
          "La Libertad",
          "Sonsonate",
          "Ahuachapán",
          "Chalatenango",
          "Suchitoto",
          "Ilobasco",
          "Juayúa"
        ]
      },
      {
        "Country": "Grenada",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Saint George's",
          "Grenville",
          "Gouyave",
          "Carriacou",
          "Petite Martinique"
        ]
      },
      {
        "Country": "Guatemala",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Guatemala City",
          "Antigua",
          "Chichicastenango",
          "Lake Atitlán",
          "Quetzaltenango",
          "Tikal",
          "Puerto San José",
          "Mazatenango",
          "Escuintla",
          "Flores"
        ]
      },
      {
        "Country": "Honduras",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Tegucigalpa",
          "San Pedro Sula",
          "La Ceiba",
          "Copán Ruinas",
          "Roatán",
          "Utila",
          "Guanaja",
          "Omoa",
          "Trujillo",
          "Tela"
        ]
      },
      {
        "Country": "Jamaica",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Kingston",
          "Montego Bay",
          "Negril",
          "Ocho Rios",
          "Port Antonio",
          "Falmouth",
          "Savanna-la-Mar",
          "Spanish Town",
          "Mandeville",
          "St. Ann's Bay"
        ]
      },
      {
        "Country": "Nicaragua",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Managua",
          "Granada",
          "León",
          "San Juan del Sur",
          "Ometepe",
          "Masaya",
          "Estelí",
          "Bluefields",
          "Puerto Cabezas",
          "Juigalpa"
        ]
      },
      {
        "Country": "Panama",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival, Consulate application (for some purposes)",
        "Cities": [
          "Panama City",
          "Colón",
          "Bocas del Toro",
          "David",
          "Boquete",
          "San Blas Islands",
          "Santa Catalina",
          "Pedasí",
          "Chitre",
          "Las Tablas",
        ]
      },
      {
        "Country": "Saint Kitts and Nevis",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Basseterre",
          "Charlestown",
        ]
      },
      {
        "Country": "Saint Lucia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Castries",
          "Gros Islet",
          "Soufrière",
          "Vieux Fort",
        ]
      },
      {
        "Country": "Saint Vincent and the Grenadines",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Kingstown",
          "Bequia",
          "Mustique",
          "Canouan",
          "Union Island",
          "Chateaubelair",
          "Barrouallie",
          "Port Elizabeth",
          "Layou",
        ]
      },
      {
        "Country": "Trinidad and Tobago",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "eVisa, Visa on arrival",
        "Cities": [
          "Port of Spain",
          "San Fernando",
          "Chaguanas",
          "Arima",
          "Point Fortin",
          "Scarborough",
          "Tunapuna",
          "Moruga",
          "Rio Claro",
          "Princes Town",
        ]
      }
    ]
  },
  {
    "Continent": "South America",
    "countries": [
      {
        "Country": "Argentina",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, eVisa (for some countries)",
        "Cities": [
          "Buenos Aires",
          "Córdoba",
          "Rosario",
          "Mendoza",
          "Salta",
          "Ushuaia",
          "Mar del Plata",
          "La Plata",
          "Santa Fe",
          "Tucumán",
        ]
      },
      {
        "Country": "Bolivia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "La Paz",
          "Santa Cruz de la Sierra",
          "Cochabamba",
          "Sucre",
          "Oruro",
          "Potosí",
          "Tarija",
          "El Alto",
          "Beni",
          "Pando",
        ]
      },
      {
        "Country": "Brazil",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, eVisa, Visa on arrival (for some countries)",
        "Cities": [
          "São Paulo",
          "Rio de Janeiro",
          "Brasília",
          "Salvador",
          "Belo Horizonte",
          "Fortaleza",
          "Curitiba",
          "Manaus",
          "Recife",
          "Porto Alegre",
        ]
      },
      {
        "Country": "Chile",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Santiago",
          "Valparaíso",
          "Viña del Mar",
          "Concepción",
          "Antofagasta",
          "Iquique",
          "Puerto Montt",
          "Arica",
          "Punta Arenas",
          "Temuco",
        ]
      },
      {
        "Country": "Colombia",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Bogotá",
          "Medellín",
          "Cali",
          "Barranquilla",
          "Cartagena",
          "Bucaramanga",
          "Pereira",
          "Cúcuta",
          "Ibagué",
          "Manizales",
        ]
      },
      {
        "Country": "Ecuador",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Quito",
          "Guayaquil",
          "Cuenca",
          "Loja",
          "Manta",
          "Ambato",
          "Portoviejo",
          "Esmeraldas",
          "Machala",
          "Riobamba",
        ]
      },
      {
        "Country": "Guyana",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Georgetown",
          "Linden",
          "New Amsterdam",
          "Bartica",
          "Anna Regina",
          "Lethem",
          "Mahdia",
          "Parika",
          "Kwakwani",
          "Orealla",
        ]
      },
      {
        "Country": "Paraguay",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Asunción",
          "Ciudad del Este",
          "Luque",
          "San Lorenzo",
          "Lambaré",
          "Fernando de la Mora",
          "Capiatá",
          "Mariano Roque Alonso",
          "Itauguá",
          "Pedro Juan Caballero",
        ]
      },
      {
        "Country": "Peru",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Lima",
          "Arequipa",
          "Trujillo",
          "Cusco",
          "Chiclayo",
          "Iquitos",
          "Piura",
          "Huancayo",
          "Puno",
          "Tacna",
        ]
      },
      {
        "Country": "Suriname",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Paramaribo",
          "Lelydorp",
          "Nieuw Nickerie",
          "Albina",
          "Moengo",
          "Brokopondo",
          "Zanderij",
          "Nickerie",
          "Mariënburg",
          "Apoera",
        ]
      },
      {
        "Country": "Uruguay",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, eVisa (for some countries)",
        "Cities": [
          "Montevideo",
          "Punta del Este",
          "Colonia del Sacramento",
          "Salto",
          "Paysandú",
          "Maldonado",
          "Rivera",
          "Artigas",
          "Durazno",
          "Rocha",
        ]
      },
      {
        "Country": "Venezuela",
        "Recommended Months": ['May', 'June', 'July', 'August', 'September'],
        "Visa Details": "Consulate application, Visa on arrival (for some countries)",
        "Cities": [
          "Caracas",
          "Maracaibo",
          "Valencia",
          "Barquisimeto",
          "Maracay",
          "Ciudad Guayana",
          "Cumaná",
          "San Cristóbal",
          "Barinas",
          "Maturín",
        ]
      }
    ]
  },
  {
    "Continent": "Oceania",
    "countries": [
      {
        "Country": "Australia",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Consulate application, eVisitor visa, ETA",
        "Cities": [
          "Sydney",
          "Melbourne",
          "Brisbane",
          "Perth",
          "Adelaide",
          "Gold Coast",
          "Newcastle",
          "Canberra",
          "Hobart",
          "Townsville",
          "Cairns",
          "Darwin",
          "Geelong",
          "Sunshine Coast",
          "Central Coast"
        ]
      },
      {
        "Country": "New Zealand",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Consulate application, eVisa, Visa on arrival (for some purposes)",
        "Cities": [
          "Auckland",
          "Wellington",
          "Christchurch",
          "Queenstown",
          "Rotorua",
          "Taupo",
          "Dunedin",
          "Nelson",
          "Napier",
          "Tauranga",
          "Hamilton",
          "Greymouth",
          "Wanaka",
          "Picton",
          "Franz Josef"
        ]
      },
      {
        "Country": "Fiji",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Suva",
          "Nadi",
          "Lautoka",
          "Savusavu",
          "Taveuni",
          "Kadavu",
          "Mamanuca Islands",
          "Yasawa Islands",
          "Taveuni Island",
          "Beqa Island",
          "Vanua Levu",
          "Ovalau Island",
          "Kadavu Island",
          "Lau Group",
          "Lomaiviti Group"
        ]
      },
      {
        "Country": "Solomon Islands",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Honiara",
          "Gizo",
          "Munda",
          "Kirakira",
          "Noro",
          "Auki",
          "Lata",
          "Savona",
          "Malaita",
          "Guadalcanal",
          "Choiseul",
          "Malaita",
          "Santa Isabel",
          "Temotu",
          "Rennell and Bellona"
        ]
      },
      {
        "Country": "Vanuatu",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa not required for certain purposes",
        "Cities": [
          "Port Vila",
          "Luganville",
          "Santo",
          "Efate",
          "Tanna",
          "Malekula",
          "Pentecost",
          "Ambrym",
          "Epi",
          "Erromango",
          "Vanua Lava",
          "Gaua",
          "Maewo",
          "Anatom",
          "Paama"
        ]
      },
      {
        "Country": "Samoa",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Apia",
          "Salelologa",
          "Mulifanua",
          "Upolu",
          "Savai'i",
          "Manono",
          "Apolima",
          "Savai'i Island",
          "Upolu Island",
          "Manono Island",
          "Apolima Island",
          "Fagaloa Bay",
          "Lalomanu",
          "Salelologa",
          "Aleipata Islands"
        ]
      },
      {
        "Country": "Cook Islands",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa not required for certain purposes",
        "Cities": [
          "Rarotonga",
          "Aitutaki",
          "Atiu",
          "Mangaia",
          "Mauke",
          "Mitiaro",
          "Rarotonga Island",
          "Aitutaki Island",
          "Atiu Island",
          "Mangaia Island",
          "Mauke Island",
          "Mitiaro Island",
          "Palmerston Island",
          "Manihiki Island",
          "Penrhyn Island"
        ]
      },
      {
        "Country": "Kiribati",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Tarawa Atoll",
          "Kiritimati Island",
          "Tabuaeran Island",
          "Abemama Island",
          "Maiana Island",
          "Aranuka Island",
          "Nonouti Island",
          "Beru Island",
          "Nikunau Island",
          "Butaritari Island",
          "Onotoa Island",
          "Tamana Island",
          "Kuria Island",
          "Aranuka Island",
          "Marakei Island"
        ]
      },
      {
        "Country": "Tuvalu",
        "Recommended Months": ['April', 'May', 'June', 'July', 'August', 'September', 'October'],
        "Visa Details": "Visa on arrival / eVisa, Consulate application (for some purposes)",
        "Cities": [
          "Funafuti",
          "Vaiaku Village",
          "Nanumea",
          "Niutao",
          "Nukulaelae",
          "Vaitupu",
          "Nukufetau",
          "Nanumanga",
          "Niulakita",
          "Nui Island",
          "Nanumea Island",
          "Vaitupu Island",
          "Nukufetau Island",
          "Nanumanga Island",
          "Niulakita"
        ]
      }
    ]
  }
]