export const Countries: string[] = [

    'Asia',
    'Europe',
    'Africa',
    'North America',
    'South America',
    'Oceania',
    'Indonesia',
    'Israel',
    'Japan',
    'Kazakhstan',
    'Kyrgyzstan',
    'Laos',
    'Lebanon',
    'Malaysia',
    'Philippines',
    'Singapore',
    'South Korea',
    'Thailand',
    'United Arab Emirates',
    'Albania',
    'Andorra',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Czech Republic',
    'Denmark',
    'Estonia',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'North Macedonia',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Algeria',
    'Angola',
    'Botswana',
    'Burundi',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Democratic Republic of the Congo',
    'Republic of the Congo',
    'Egypt',
    'Equatorial Guinea',
    'Eritrea',
    'Gambia',
    'Ghana',
    'Guinea',
    'Liberia',
    'Libya',
    'Mauritius',
    'Morocco',
    'Niger',
    'Nigeria',
    'Republic of the Congo',
    'Seychelles',
    'Sierra Leone',
    'South Africa',
    'South Sudan',
    'Sudan',
    'Swaziland',
    'Tunisia',
    'Canada',
    'United States',
    'Mexico',
    'Greenland',
    'Saint Pierre and Miquelon',
    'Antigua and Barbuda',
    'Bahamas',
    'Barbados',
    'Belize',
    'Costa Rica',
    'Cuba',
    'Dominica',
    'Dominican Republic',
    'El Salvador',
    'Grenada',
    'Guatemala',
    'Honduras',
    'Jamaica',
    'Nicaragua',
    'Panama',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Trinidad and Tobago',
    'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
    'Australia',
    'New Zealand',
    'Fiji',
    'Solomon Islands',
    'Vanuatu',
    'Samoa',
    'Cook Islands',
    'Kiribati',
    'Tuvalu',
    'Jakarta',
    'Jerusalem',
    'Tokyo',
    'Nur-Sultan',
    'Bishkek',
    'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar (Burma)', 'Nepal', 'North Korea', 'Oman', 'Philippines', 'Qatar', 'Russia', 'Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Taiwan', 'Tajikistan', 'Thailand', 'Timor-Leste', 'Turkey', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam','Yemen',
    'Amman', 'Petra', 'Wadi Rum', 'Madaba', 'Jerash', 'Karak', 'Aqaba', 'Ajloun', 'Al Salt', 'Irbid', 'Zarqa', 'Ma`an', 'Tafileh', 'Tafila', 'Umm Qays','Kuwait City', 'Al Ahmadi', 'Hawalli', 'Jahra', 'Farwaniya', 'Mubarak Al-Kabeer', 'Ahmadi', 'Salmiya', 'Mangaf', 'Wafra', 'Abdali', 'Jahra (Kuwait City)', 'Doha (Kuwait City)', 'Mishrif', 'Riqqa','Male', 'Hulhumale', 'Addu City',
    'Fuvahmulah', 'Thinadhoo', 'Kudahuvadhoo', 'Naifaru', 'Madivaru', 'Gan', 'Villingili', 'Male (Kaafu)', 'Mahibadhoo', 'Thulusdhoo', 'Meedhoo', 'Ukulhas',
    'Ulaanbaatar', 'Erdenet', 'Moron', 'Karakorum', 'Khovd', 'Darkhan', 'Bulgan', 'Ulaanbaatar (Selenge)', 'Khentii', 'Sukhbaatar', 'Orkhon', 'Darhan (Orkhon)', 'Ondorkhaan', 'Sainshand', 'Dzud-Durgun',
'Yangon', 'Mandalay', 'Nay Pyi Taw', 'Bagan', 'Inle Lake', 'Hpaung Daw U', 'Kalaw', 'Mawlamyine', 'Dawei', 'Myeik', 'Taungoo', 'Monywa', 'Kengtung', 'Lashio', 'Hsipaw',
'Kathmandu', 'Pokhara', 'Lumbini', 'Patan', 'Bhaktapur', 'Nagarkot', 'Chitwan National Park', 'Gorkha', 'Bandipur', 'Lumbini (Rupandehi)', 'Mustang', 'Dolpo', 'Manang', 'Mustang (Mustang)', 'Dolpo (Dolpo)',
'Pyongyang', 'Wonsan', 'Kaesong', 'Hamhung', 'Chongjin', 'Nampo', 'Sariwon', 'Sinuiju', 'Chongjin', 'Hyesan', 'Rason', 'Anju', 'Tokchon', 'Pyongsong', 'Kaechon',
'Muscat', 'Salalah', 'Nizwa', 'Sur', 'Rustaq', 'Sohar', 'Barka', 'Ibra', 'Jebel Akhdar', 'Quriyat', 'Bidbid', 'Al Hamra', 'Manah', 'Dima W`attaiyin', 'Bahla',
'Doha', 'Al Wakrah', 'Al Khor', 'Al Rayyan', 'Umm Salal', 'Madinat ash Shamal', 'Al Khor', 'Al Daayen', 'Al Ghariyah', 'Al Khawr', 'Mesaimeer', 'Al Wakrah', 'Al Sailiya', 'Al Aziziyah',
'Moscow', 'St. Petersburg', 'Sochi', 'Yekaterinburg', 'Nizhny Novgorod', 'Kazan', 'Samara', 'Rostov-on-Don', 'Ufa', 'Krasnodar', 'Vladivostok', 'Volgograd', 'Chelyabinsk', 'Saratov', 'Voronezh',
'Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Taif', 'Khobar', 'Abha', 'Tabuk', 'Yanbu', 'Jubail', 'Hail', 'Buraidah', 'Qassim', 'Al-Ahsa',
'Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo', 'Trincomalee', 'Matara', 'Kalutara', 'Dambulla', 'Anuradhapura', 'Polonnaruwa', 'Kandy (Sri Lanka)', 'Galle (Sri Lanka)', 'Jaffna (Sri Lanka)',
'Damascus', 'Aleppo', 'Latakia', 'Homs', 'Hama', 'Daraa', 'Tartus', 'Deir ez-Zor', 'Al-Hasakah', 'Raqqa', 'Idlib', 'Qamishli', 'As-Suwayda', 'Al-Ma`arrat an-Nu`man',
'Taipei', 'Kaohsiung', 'Taichung', 'Taoyuan', 'Hsinchu', 'Keelung', 'Tainan', 'Changhua', 'Chiayi', 'Taitung', 'Yilan', 'Nantou', 'Hualien', 'Penghu',
'Dushanbe', 'Khujand', 'Istaravshan', 'Kulob', 'Khorog', 'Penjikent', 'Tursunzoda', 'Panjakent', 'Nurek', 'Hissar', 'Bokhtar', 'Kurgan-Tyube', 'Fayzobod', 'Ayni', 'Rasht',
'Dili', 'Baucau', 'Liquica', 'Manatuto', 'Same', 'Maliana', 'Viqueque', 'Oecusse', 'Ainaro', 'Bobonaro', 'Ermera', 'Aileu', 'Manufahi', 'Lautém',
'Ashgabat', 'Turkmenabat', 'Dashoguz', 'Mary', 'Türkmenbashi', 'Balkanabat', 'Ahal', 'Lebap', 'Dashoguz (Turkmenistan)', 'Balkan (Turkmenistan)', 'Mary (Turkmenistan)', 'Ahal (Turkmenistan)', 'Lebap (Turkmenistan)', 'Dashoguz (Turkmenistan)',
'Tashkent', 'Samarkand', 'Bukhara', 'Khiva', 'Namangan', 'Fergana', 'Andijan', 'Nukus', 'Termez', 'Jizzakh', 'Navoi', 'Qarshi', 'Bukhara (Uzbekistan)', 'Samarkand (Uzbekistan)',
'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Haiphong', 'Hue', 'Can Tho', 'Da Lat', 'Phu Quoc', 'Vung Tau', 'Quy Nhon', 'Hue (Vietnam)', 'Haiphong (Vietnam)', 'Can Tho (Vietnam)', 'Da Lat (Vietnam)', 'Nha Trang (Vietnam)',
'Sanaa', 'Aden', 'Taiz', 'Hodeidah', 'Ibb', 'Sa`dah', 'Dhamar', 'Marib', 'Al Hudaydah', 'Hajjah', 'Ta`izz', 'Amran', 'Raymah', 'Al Jawf', 'Ma`rib (Yemen)', 
'Luang Prabang',
'Beirut',
'Kuala Lumpur',
'Manila',
'Singapore',
'Seoul',
'Bangkok',
'Dubai',
'Tirana',
'Andorra la Vella',
'Vienna',
'Minsk',
'Brussels',
'Sarajevo',
'Sofia',
'Zagreb',

'Prague',
'Copenhagen',
'Tallinn',
'Helsinki',
'Paris',
'Berlin',
'Athens',
'Budapest',
'Reykjavík',
'Dublin',
'Rome',
'Pristina',
'Riga',
'Vaduz',
'Vilnius',
'Luxembourg City',
'Skopje',
'Valletta',
'Chișinău',
'Monaco',
'Podgorica',
'Amsterdam',
'Oslo',
'Warsaw',
'Lisbon',
'Bucharest',
'Moscow',
'San Marino',
'Belgrade',
'Bratislava',
'Ljubljana',
'Madrid',
'Stockholm',
'Zürich',
'Oran',
'Huambo',
'Francistown',
'Gitega',
'Douala',
'Berberati',
'Moundou',
'Lubumbashi',
'Pointe-Noire',
'Alexandria',
'Bata',
'Massawa',
'Serekunda',
'Kumasi',
'Kankan',
'Gbarnga',
'Benghazi',
'Curepipe',
'Rabat',
'Zinder',
'Abuja',
'Mahé',
'Bo',
'Cape Town',
'Wau',
'Omdurman',
'Manzini',
'Sousse',
'Toronto',
'New York City',
'Mexico City',
'Nuuk',
'Saint-Pierre',
'Saint Johns',
'Nassau',
'Bridgetown',
'Belize City',
'San José',
'Havana',
'Roseau',
'Santo Domingo',
'San Salvador',
'Saint Georges',
'Guatemala City',
'Tegucigalpa',
'Kingston',
'Managua',
'Panama City',
'Basseterre',
'Castries',
'Kingstown',
'Port of Spain',
'Buenos Aires',
'La Paz',
'São Paulo',
'Santiago',
'Bogotá',
'Quito',
'Georgetown',
'Asunción',
'Lima',
'Paramaribo',
'Montevideo',
'Caracas',
'Sydney',
'Auckland',
'Suva',
'Honiara',
'Port Vila',
'Apia',
'Rarotonga',
'Tarawa Atoll',
'Funafuti',
'Bali',
'Tel Aviv',
'Kyoto',
'Almaty',
'Osh',
'Vientiane',
'Tyre',
'Cebu',
'Johor Bahru',
'Busan',
'Phuket',
'Abu Dhabi',
'Durrës',
'Escaldes-Engordany',
'Salzburg',
'Brest',
'Antwerp',
'Mostar',
'Plovdiv',
'Split',
'Brno',
'Århus',
'Tartu',
'Tampere',
'Marseille',
'Munich',
'Thessaloniki',
'Debrecen',
'Akureyri',
'Cork',
'Milan',
'Prizren',
'Daugavpils',
'Schaan',
'Kaunas',
'Esch-sur-Alzette',
'Bitola',
'Birgu',
'Tiraspol',
'Monte Carlo',
'Nikšić',
'Rotterdam',
'Bergen',
'Kraków',
'Porto',
'Cluj-Napoca',
'Saint Petersburg',
'Borgo Maggiore',
'Novi Sad',
'Košice',
'Maribor',
'Barcelona',
'Gothenburg',
'Geneva',
'Constantine',
'Benguela',
'Maun',
'Ngozi',
'Garoua',
'Bouar',
'Sarh',
'Mbuji-Mayi',
'Giza',
'Ebebiyín',
'Keren',
'Brikama',
'Takoradi',
'Kindia',
'Buchanan',
'Misrata',
'Quatre Bornes',
'Fez',
'Maradi',
'Kano',
'Dolisie',
'Praslin',
'Kenema',
'Durban',
'Malakal',
'Port Sudan',
'Nhlangano',
'Sfax',
'Vancouver',
'Los Angeles',
'Cancun',
'Ilulissat',
'Miquelon',
'Codrington',
'Freeport',
'Speightstown',
'San Ignacio',
'Liberia',
'Santiago de Cuba',
'Portsmouth',
'Punta Cana',
'Santa Ana',
'Grenville',
'Antigua',
'San Pedro Sula',
'Montego Bay',
'Granada',
'Colón',
'Charlestown',
'Gros Islet',
'Bequia',
'San Fernando',
'Córdoba',
'Santa Cruz de la Sierra',
'Rio de Janeiro',
'Valparaíso',
'Medellín',
'Guayaquil',
'Linden',
'Ciudad del Este',
'Arequipa',
'Lelydorp',
'Punta del Este',
'Maracaibo',
'Melbourne',
'Wellington',
'Nadi',
'Gizo',
'Luganville',
'Salelologa',
'Aitutaki',
'Kiritimati Island',
'Vaiaku Village',
'Surabaya',
'Haifa',
'Osaka',
'Shymkent',
'Karakol',
'Vang Vieng',
'Sidon',
'Malacca',
'Davao',
'Malacca',
'Jeju',
'Chiang Mai',
'Sharjah',
'Shkodra',
'La Massana',
'Innsbruck',
'Gomel',
'Bruges',
'Banja Luka',
'Varna',
'Dubrovnik',
'Ostrava',
'Odense',
'Narva',
'Turku',
'Lyon',
'Frankfurt am Main',
'Patras',
'Miskolc',
'Selfoss',
'Galway',
'Naples',
'Peja',
'Liepāja',
'Triesen',
'Klaipėda',
'Differdange',
'Prilep',
'Sliema',
'Bălți',
'Fontvieille',
'Budva',
'The Hague',
'Trondheim',
'Gdańsk',
'Faro',
'Timișoara',
'Sochi',
'Serravalle',
'Niš',
'Prešov',
'Celje',
'Valencia',
'Malmö',
'Basel',
'Annaba',
'Lubango',
'Molepolole',
'Rumonge',
'Bamenda',
'Bossangoa',
'Abéché',
'Kananga',
'Luxor',
'Mongomo',
'Dekemhare',
'Bakau',
'Tamale',
'NZérékoré',
'Kakata',
'Sebha',
'Mahébourg',
'Meknes',
'Agadez',
'Ibadan',
'Nkayi',
'La Digue',
'Makeni',
'Pretoria',
'Bor',
'El-Fasher',
'Big Bend',
'Kairouan',
'Montreal',
'Chicago',
'Guadalajara',
'Qaqortoq',
'Holetown',
'Placencia',
'Puerto Viejo',
'Varadero',
'Marigot',
'Puerto Plata',
'San Miguel',
'Gouyave',
'Chichicastenango',
'La Ceiba',
'Negril',
'León',
'Bocas del Toro',
'Soufrière',
'Mustique',
'Chaguanas',
'Rosario',
'Cochabamba',
'Brasília',
'Viña del Mar',
'Cali',
'Cuenca',
'New Amsterdam',
'Luque',
'Trujillo',
'Nieuw Nickerie',
'Colonia del Sacramento',
'Valencia',
'Brisbane',
'Christchurch',
'Lautoka',
'Munda',
'Santo',
'Mulifanua',
'Atiu',
'Tabuaeran Island',
'Nanumea',
'Medan',
'Eilat',
'Yokohama',
'Astana',
'Jalalabad',
'Luang Namtha',
'Tripoli',
'Johor Bahru',
'Angeles',
'Penang',
'Daegu',
'Pattaya',
'Ajman',
'Berat',
'Sant Julià de Lòria',
'Graz',
'Vitebsk',
'Ghent',
'Tuzla',
'Burgas',
'Zadar',
'Plzeň',
'Aalborg',
'Pärnu',
'Espoo',
'Nice',
'Hamburg',
'Heraklion',
'Szeged',
'Hafnarfjörður',
'Limerick',
'Florence',
'Gjilan',
'Jūrmala',
'Balzers',
'Šiauliai',
'Dudelange',
'Tetovo',
'St. Julians',
'Bender',
'La Condamine',
'Kotor',
'Utrecht',
'Stavanger',
'Wrocław',
'Albufeira',
'Iași',
'Kazan',
'Domagnano',
'Kragujevac',
'Žilina',
'Kranj',
'Seville',
'Uppsala',
'Bern',
'Batna',
'Namibe',
'Selibe Phikwe',
'Kayanza',
'Nkongsamba',
'Sibut',
'Faya-Largeau',
'Kisangani',
'Aswan',
'Luba',
'Barentu',
'Farafenni',
'Sunyani',
'Labé',
'Zwedru',
'Al Bayda',
'Grand Port',
'Tahoua',
'Port Harcourt',
'Silhouette',
'Lunsar',
'Soweto',
'Rumbek',
'Wadi Halfa',
'Piggs Peak',
'Bizerte',
'Calgary',
'Miami',
'Monterrey',
'Sisimiut',
'Marsh Harbour',
'Oistins',
'Caye Caulker',
'Tamarindo',
'Cienfuegos',
'La Romana',
'La Libertad',
'Carriacou',
'Lake Atitlán',
'Copán Ruinas',
'Ocho Rios',
'San Juan del Sur',
'David',
'Vieux Fort',
'Canouan',
'Arima',
'Mendoza',
'Sucre',
'Salvador',
'Concepción',
'Barranquilla',
'Loja',
'Bartica',
'San Lorenzo',
'Cusco',
'Albina',
'Salto',
'Barquisimeto',
'Perth',
'Queenstown',
'Savusavu',
'Kirakira',
'Efate',
'Upolu',
'Mangaia',
'Abemama Island',
'Niutao',
'Bandung',
'Tiberias',
'Kamakura',
'Aktobe',
'Naryn',
'Pakse',
'Baalbek',
'Ipoh',
'Bacolod',
'George Town',
'Gwangju',
'Surat Thani',
'Ras Al Khaimah',
'Kruja',
'Pas de la Casa',
'Klagenfurt',
'Mogilev',
'Liège',
'Zenica',
'Ruse',
'Rijeka',
'Kyrenia',
'Liberec',
'Esbjerg',
'Kohtla-Järve',
'Vantaa',
'Toulouse',
'Cologne',
'Nafplio',
'Pécs',
'Garðabær',
'Waterford',
'Venice',
'Ferizaj',
'Valmiera',
'Triesenberg',
'Panevėžys',
'Wiltz',
'Kumanovo',
'Qormi',
'Ungheni',
'La Turbie',
'Bar',
'Eindhoven',
'Tromsø',
'Łódź',
'Funchal',
'Constanța',
'Nizhny Novgorod',
'Fiorentino',
'Subotica',
'Banská Bystrica',
'Koper',
'Zaragoza',
'Västerås',
'Lausanne',
'Sétif',
'Saurimo',
'Kanye',
'Muramvya',
'Limbe',
'Kaga-Bandoro',
'Doba',
'Bukavu',
'El-Mansura',
'Oyala',
'Mendefera',
'Mbak',
'Koforidua',
'Mamou',
'Ganta',
'Derna',
'Rose-Hill',
'Dosso',
'Kaduna',
'Gamboma',
'Curieuse',
'Port Loko',
'Port Elizabeth',
'Yei',
'Atbara',
'Siteki',
'Djerba',
'Ottawa',
'Houston',
'Puebla',
'Maniitsoq',
'Exuma',
'Ambergris Caye',
'Manuel Antonio',
'Trinidad',
'Samaná',
'Sonsonate',
'Petite Martinique',
'Quetzaltenango',
'Roatán',
'Port Antonio',
'Ometepe',
'Boquete',
'Union Island',
'Point Fortin',
'Salta',
'Oruro',
'Belo Horizonte',
'Antofagasta',
'Cartagena',
'Manta',
'Anna Regina',
'Lambaré',
'Chiclayo',
'Moengo',
'Paysandú',
'Maracay',
'Adelaide',
'Rotorua',
'Taveuni',
'Noro',
'Tanna',
'Savaii',
'Mauke',
'Maiana Island',
'Nukulaelae',
'Semarang',
'Safed',
'Nara',
'Karaganda',
'Talas',
'Savannakhet',
'Byblos',
'Kuching',
'Iloilo City',
'Ipoh',
'Incheon',
'Hat Yai',
'Fujairah',
'Vlorë',
'Encamp',
'Bregenz',
'Grodno',
'Namur',
'Goražde',
'Stara Zagora',
'Osijek',
'Famagusta',
'Olomouc',
'Randers',
'Viljandi',
'Oulu',
'Bordeaux',
'Stuttgart',
'Santorini',
'Tihany',
'Keflavík',
'Sligo',
'Turin',
'Mitrovica',
'Ventspils',
'Eschen',
'Alytus',
'Ettelbruck',
'Mdina',
'Cahul',
'Roquebrune-Cap-Martin',
'Ulcinj',
'Groningen',
'Kristiansand',
'Poznań',
'Évora',
'Craiova',
'Yekaterinburg',
'Acquaviva',
'Čačak',
'Trnava',
'Novo Mesto',
'Málaga',
'Örebro',
'Winterthur',
'Blida',
'Malanje',
'Jwaneng',
'Bukavu',
'Buea',
'Mbaïki',
'Mongo',
'Kolwezi',
'Port Said',
'Aconibe',
'Adi Keyh',
'Kombo Saint Mary',
'Cape Coast',
'Faranah',
'Harper',
'Tobruk',
'Vacoas-Phoenix',
'Tillabéri',
'Benin City',
'Madingou',
'Cousine',
'Magburaka',
'Bloemfontein',
'Bentiu',
'Nyala',
'Lavumisa',
'Zarzis',
'Quebec City',
'San Francisco',
'Tijuana',
'Narsarsuaq',
'Eleuthera',
'Corozal',
'Monteverde',
'Holguín',
'Bayahibe',
'Ahuachapán',
'Tikal',
'Utila',
'Falmouth',
'Masaya',
'San Blas Islands',
'Chateaubelair',
'Scarborough',
'Ushuaia',
'Potosí',
'Fortaleza',
'Iquique',
'Bucaramanga',
'Ambato',
'Lethem',
'Fernando de la Mora',
'Iquitos',
'Brokopondo',
'Maldonado',
'Ciudad Guayana',
'Gold Coast',
'Taupo',
'Kadavu',
'Auki',
'Malekula',
'Manono',
'Mitiaro',
'Aranuka Island',
'Vaitupu',
'Yogyakarta',
'Nazareth',
'Hiroshima',
'Kostanay',
'Toktogul',
'Thakhek',
'Jounieh',
'Kota Kinabalu',
'Puerto Princesa',
'Kuala Lumpur',
'Daejeon',
'Hua Hin',
'Umm Al Quwain',
'Gjirokastër',
'Canillo',
'Linz',
'Polotsk',
'Charleroi',
'Travnik',
'Pleven',
'Pula',
'Ayia Napa',
'Hradec Králové',
'Horsens',
'Rakvere',
'Lahti',
'Nantes',
'Düsseldorf',
'Mykonos',
'Nyíregyháza',
'Drogheda',
'Palermo',
'Vushtrri',
'Rēzekne',
'Mauren',
'Marijampolė',
'Diekirch',
'Štip',
'Mosta',
'Comrat',
'Cap-dAil',
'Tivat',
'Almere',
'Drammen',
'Szczecin',
'Coimbra',
'Brașov',
'Samara',
'Faetano',
'Kragujevac',
'Nitra',
'Velenje',
'Bilbao',
'Linköping',
'Lucerne',
'Tlemcen',
'Uíge',
'Orapa',
'Rutana',
'Maroua',
'Nola',
'Bongor',
'Goma',
'Suez',
'Riaba',
'Kuntaur',
'Sekondi-Takoradi',
'Siguiri',
'Tubmanburg',
'Ghadames',
'Rodrigues',
'Gouré',
'Maiduguri',
'Ntoumpa',
'Farquhar',
'Kambia',
'East London',
'Torit',
'Kassala',
'Matsapha',
'Tozeur',
'Edmonton',
'Philadelphia',
'Puerto Vallarta',
'Uummannaq',
'Harbour Island',
'Punta Gorda',
'La Fortuna',
'Camagüey',
'Barahona',
'Chalatenango',
'Puerto San José',
'Guanaja',
'Savanna-la-Mar',
'Estelí',
'Santa Catalina',
'Barrouallie',
'Tunapuna',
'Mar del Plata',
'Tarija',
'Curitiba',
'Puerto Montt',
'Pereira',
'Portoviejo',
'Mahdia',
'Capiatá',
'Piura',
'Zanderij',
'Rivera',
'Cumaná',
'Newcastle',
'Dunedin',
'Mamanuca Islands',
'Lata',
'Pentecost',
'Apolima',
'Rarotonga Island',
'Nonouti Island',
'Nukufetau',
'Surakarta (Solo)',
'Ashdod',
'Nagasaki',
'Pavlodar',
'Kara-Suu',
'Nong Khai',
'Zahle',
'Penang',
'Zamboanga City',
'Petaling Jaya',
'Ulsan',
'Nakhon Si Thammarat',
'Al Ain',
'Saranda',
'Ordino',
'Salzburgerland',
'Slutsk',
'Mons',
'Bihać',
'Shumen',
'Šibenik',
'Protaras',
'České Budějovice',
'Kolding',
'Jõhvi',
'Tampere',
'Strasbourg',
'Dortmund',
'Chania',
'Székesfehérvár',
'Dundalk',
'Bologna',
'Skenderaj',
'Jelgava',
'Triesen',
'Tauragė',
'Vianden',
'Gostivar',
'Marsaxlokk',
'Drochia',
'Èze',
'Herceg Novi',
'Breda',
'Fredrikstad',
'Lublin',
'Braga',
'Galați',
'Rostov-on-Don',
'Chiesanuova',
'Zrenjanin',
'Poprad',
'Ptuj',
'Las Palmas de Gran Canaria',
'Norrköping',
'St. Gallen',
'Mostaganem',
'Cabinda',
'Palapye',
'Cibitoke',
'Bafoussam',
'Alindao',
'Kélo',
'Matadi',
'Ismailia',
'Mbini',
'Jarra Soma',
'Obuasi',
'Kouroussa',
'Greenville',
'Sabha',
'Flic-en-Flac',
'Birni NKonni',
'Enugu',
'Lekana',
'Aldabra',
'Koidu',
'Pietermaritzburg',
'Kapoeta',
'El Obeid',
'Mankayane',
'Mahdia',
'Winnipeg',
'Phoenix',
'Mérida',
'Tasiilaq',
'Cat Island',
'San Pedro',
'Jaco',
'Cayo Coco',
'Santiago',
'Suchitoto',
'Mazatenango',
'Omoa',
'Spanish Town',
'Bluefields',
'Pedasí',
'Port Elizabeth',
'Moruga',
'La Plata',
'El Alto',
'Manaus',
'Arica',
'Cúcuta',
'Esmeraldas',
'Parika',
'Mariano Roque Alonso',
'Huancayo',
'Nickerie',
'Artigas',
'San Cristóbal',
'Canberra',
'Nelson',
'Yasawa Islands',
'Savona',
'Ambrym',
'Savaii Island',
'Aitutaki Island',
'Beru Island',
'Nanumanga',
'Denpasar',
'Beersheba',
'Sapporo',
'Öskemen',
'Batken',
'Pakse (Champasak)',
'Akkar',
'Kuantan',
'Cagayan de Oro City',
'Klang',
'Suwon',
'Udon Thani',
'Al Dhafra',
'Ohrid',
'Arinsal',
'Tyrol',
'Neman',
'Tournai',
'Bijeljina',
'Dobrich',
'Zadar',
'Limni',
'Zlín',
'Frederiksberg',
'Kuressaare',
'Jyväskylä',
'Montpellier',
'Essen',
'Kalamata',
'Kecskemét',
'Navan',
'Genoa',
'Gjakovë',
'Jēkabpils',
'Ruggell',
'Telšiai',
'Clervaux',
'Veles',
'Rabat',
'Strășeni',
'Beausoleil',
'Cetinje',
'Nijmegen',
'Sandnes',
'Katowice',
'Setúbal',
'Ploiești',
'Volgograd',
'Montegiardino',
'Leskovac',
'Martin',
'Nova Gorica',
'Alicante',
'Helsingborg',
'Fribourg',
'Sidi Bel Abbès',
'Moxico',
'Mahalapye',
'Karuzi',
'Ngaoundéré',
'Bambari',
'Mao',
'Kikwit',
'Tanta',
'Ebebiyin',
'Gunjur',
'Wa',
'Pita',
'Robertsport',
'Ajdabiya',
'Goodlands',
'Arlit',
'Aba',
'Djambala',
'Aride',
'Segbwema',
'Nelspruit',
'Aweil',
'El Daein',
'Bulembu',
'Monastir',
'Hamilton',
'San Antonio',
'Oaxaca',
'Qasigiannguit',
'Andros',
'Dangriga',
'Nosara',
'Cayo Largo',
'Sosúa',
'Ilobasco',
'Escuintla',
'Trujillo',
'Mandeville',
'Puerto Cabezas',
'Chitre',
'Layou',
'Rio Claro',
'Santa Fe',
'Beni',
'Recife',
'Punta Arenas',
'Ibagué',
'Machala',
'Kwakwani',
'Itauguá',
'Puno',
'Mariënburg',
'Durazno',
'Barinas',
'Hobart',
'Napier',
'Taveuni Island',
'Malaita',
'Epi',
'Upolu Island',
'Atiu Island',
'Nikunau Island',
'Niulakita',
'Palembang',
'Rishon LeZion',
'Fukuoka',
'Taraz',
'Issyk-Kul',
'Huay Xai',
'Hermel',
'Petaling Jaya',
'Davao del Sur',
'Seremban',
'Changwon',
'Khon Kaen',
'Umm Al Quwain (United Arab Emirates)',
'Dajti',
'Pal',
'Vorarlberg',
'Orsha',
'Ostend',
'Zvornik',
'Gabrovo',
'Varaždin',
'Polis Chrysochous',
'Jihlava',
'Roskilde',
'Haapsalu',
'Kuopio',
'Lille',
'Leipzig',
'Rhodes',
'Zalaegerszeg',
'Longford',
'Cinque Terre',
'Fushë Kosova',
'Aizkraukle',
'Gamprin',
'Utena',
'Remich',
'Strumica',
'Naxxar',
'Orhei',
'Menton',
'Berane',
'Enschede',
'Skien',
'Białystok',
'Guimarães',
'Brăila',
'Ufa',
'Verucchio',
'Užice',
'Trenčín',
'Jesenice',
'Córdoba',
'Jönköping',
'Neuchâtel',
'Skikda',
'Cuando Cubango',
'Ghanzi',
'Bururi',
'Kumba',
'Paoua',
'Am Timan',
'Bunia',
'Sharm El Sheikh',
'Kogo',
'Basse Santa Su',
'Tarkwa',
'Impfondo',
'Gaoual',
'Sinkor',
'Al Khums',
'Triolet',
'Diffa',
'Ilorin',
'Sibiti',
'Denis',
'Waterloo',
'Rustenburg',
'Nimule',
'Dongola',
'Malkerns',
'Gabes',
'Victoria',
'Dallas',
'León',
'Aasiaat',
'Long Island',
'Hopkins',
'Quepos',
'Cayo Santa María',
'Cabarete',
'Juayúa',
'Flores',
'Tela',
'St. Anns Bay',
'Juigalpa',
'Las Tablas',
'Princes Town',
'Tucumán',
'Pando',
'Porto Alegre',
'Temuco',
'Manizales',
'Riobamba',
'Orealla',
'Pedro Juan Caballero',
'Tacna',
'Apoera',
'Rocha',
'Maturín',
'Townsville',
'Tauranga',
'Beqa Island',
'Guadalcanal',
'Erromango',
'Manono Island',
'Mangaia Island',
'Butaritari Island',
'Nui Island',
'Makassar',
'Netanya',
'Kobe',
'Semey',
'Cholpon-Ata',
'Luang Namtha (Luang Prabang)',
'Qamishli',
'Malacca (Melaka)',
'General Santos City',
'Sejong',
'Krabi',
'Ras Al Khaimah (United Arab Emirates)',
'Pogradec',
'Sant Moritz',
'Hallstatt',
'Pinsk',
'Mechelen',
'Jajce',
'Veliko Tarnovo',
'Slavonski Brod',
'Latchi',
'Karlovy Vary',
'Vejle',
'Paide',
'Pori',
'Reims',
'Dresden',
'Piraeus',
'Eger',
'Kilkenny',
'Pompeii',
'Klinë',
'Sigulda',
'Schellenberg',
'Jonava',
'Mondorf-les-Bains',
'Kavadarci',
'Mellieħa',
'Soroca',
'Pljevlja',
'Zwolle',
'Haugesund',
'Bytom',
'Nazaré',
'Sibiu',
'Krasnodar',
'Valjevo',
'Žiar nad Hronom',
'Murska Sobota',
'Valladolid',
'Halmstad',
'Lugano',
'El Oued',
'Bié',
'Letlhakane',
'Rumonge',
'Ebolowa',
'Grimari',
'Ati',
'Kindu',
'Qena',
'Niefang',
'Soma',
'Elmina',
'Dalaba',
'Sanniquellie',
'Misrata',
'Tamarin',
'Maine-Soroa',
'Warri',
'Ewo',
'Desroches',
'Moyamba',
'Polokwane',
'Bunj',
'Gedaref',
'Hhohho',
'Tataouine',
'Niagara Falls',
'Washington',
'Morelia',
'Acklins Island',
'Tortuguero',
'Darwin',
'Greymouth',
'Ovalau Island',
'Malaita',
'Gaua',
'Fagaloa Bay',
'Mitiaro Island',
'Tamana Island',
'Vaitupu Island',
'Lake Toba',
'Petah Tikva',
'Nara',
'Petropavlovsk',
'Balykchy',
'Salavan',
'Tripoli (Lebanon)',
'Seremban',
'Bacolod City',
'Chuncheon',
'Chiang Mai (Thailand)',
'Al Ain (United Arab Emirates)',
'Korçë',
'Chur',
'Kaprun',
'Kobrin',
'Hasselt',
'Konjic',
'Pernik',
'Koprivnica',
'Pardubice',
'Silkeborg',
'Võru',
'Kotka',
'Le Havre',
'Hannover',
'Corfu',
'Szombathely',
'Wexford',
'Sorrento',
'Deçan',
'Cēsis',
'Planken',
'Ukmergė',
'Pétange',
'Negotino',
'Żebbuġ',
'Rezina',
'Bijelo Polje',
'Maastricht',
'Lillehammer',
'Toruń',
'Portimão',
'Bacău',
'Perm',
'Smederevo',
'Nové Zámky',
'Škofja Loka',
'Vigo',
'Sundsvall',
'Interlaken',
'Tiaret',
'Lunda Norte',
'Tsabong',
'Cankuzo',
'Foumban',
'Birao',
'Oum Hadjer',
'Uvira',
'Sohag',
'Sipopo',
'Niani',
'Nkawkaw',
'Dabola',
'Karnplay',
'Ubari',
'Le Morne',
'Abala',
'Abeokuta',
'Bird',
'Bonthe',
'Secunda',
'Nasir',
'Shendi',
'Matsamo',
'El Kef',
'Thunder Bay',
'D.C.',
'Cuernavaca',
'Geelong',
'Wanaka',
'Kadavu Island',
'Santa Isabel',
'Maewo',
'Lalomanu',
'Palmerston Island',
'Kuria Island',
'Nukufetau Island',
'Borobudur',
'Bnei Brak',
'Sapporo',
'Taldykorgan',
'Son-Kul',
'Champasak',
'Sour',
'Cyberjaya',
'Dumaguete City',
'Anyang',
'Pattaya (Thailand)',
'Al Dhafra (United Arab Emirates)',
'Elbasan',
'Scuol',
'Bad Gastein',
'Vitebsk',
'Aalst',
'Foča',
'Haskovo',
'Karlovac',
'Polis Chrysochous',
'Kladno',
'Helsingør',
'Tapa',
'Mikkeli',
'Saint-Étienne',
'Nürnberg',
'Agrinio',
'Nagykanizsa',
'Wicklow',
'Amalfi Coast',
'Malishevë',
'Kuldīga',
'Triesenberg',
'Raseiniai',
'Differdange',
'Delčevo',
'Gozo',
'Taraclia',
'Apeldoorn',
'Sarpsborg',
'Zabrze',
'Vila Nova de Gaia',
'Arad',
'Voronezh',
'Vranje',
'Michalovce',
'Ilirska Bistrica',
'Gijón',
'Umeå',
'Zermatt',
'Ghardaïa',
'Lunda Sul',
'Ramotswa',
'Gihanga',
'Kribi',
'Zemio',
'Salal',
'Kalemie',
'Minya',
'Nsok',
'Ho',
'Yomou',
'Sasstown',
'Zuwarah',
'Filingué',
'Oyo',
'Makoua',
'Frégate',
'Yengema',
'Mbombela',
'Maridi',
'Port Sudan',
'Mhlume',
'Sidi Bou Said',
'Saskatoon',
'Boston',
'Veracruz',
'Sunshine Coast',
'Picton',
'Lau Group',
'Temotu',
'Anatom',
'Salelologa',
'Manihiki Island',
'Aranuka Island',
'Nanumanga Island',
'Lombok',
'Holon',
'Hakone',
'Kyzylorda',
'Tyup',
'Nabatieh',
'Miri',
'Cotabato City',
'Cheonan',
'Ajman (United Arab Emirates)',
'Kukës',
'Zermatt',
'Eisenstadt',
'Novopolotsk',
'Genk',
'Goražde',
'Sliven',
'Gospić',
'Teplice',
'Næstved',
'Sillamäe',
'Joensuu',
'Grenoble',
'Duisburg',
'Preveza',
'Szolnok',
'Kerry',
'Pisa',
'Rahovec',
'Talsi',
'Malbun',
'Radviliškis',
'Mamer',
'Gevgelija',
'Tarxien',
'Leova',
'Tilburg',
'Halden',
'Kielce',
'Sines',
'Pitești',
'Saratov',
'Šabac',
'Galanta',
'Trbovlje',
'Santander',
'Borås',
'St. Moritz',
'Windsor',
'Atlanta',
'San Miguel de Allende',
'Central Coast',
'Franz Josef',
'Lomaiviti Group',
'Rennell and Bellona',
'Paama',
'Aleipata Islands',
'Penrhyn Island',
'Marakei Island',
'Sihanoukville (Kampot)',
'Niulakita',
'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei', 'Cambodia', 'China', 'Cyprus', 'Georgia', 'India','Yerevan', 'Gyumri', 
'Vanadzor', 'Sevan', 'Dilijan', 'Etchmiadzin', 'Kapan', 'Ashtarak', 'Hrazdan', 'Abovyan', 'Sisian', 'Vayk', 'Martuni', 'Chambarak', 'Ijevan',
'Baku', 'Ganja', 'Sumqayit', 'Sheki', 'Quba', 'Lankaran', 'Mingachevir', 'Naxçivan', 'Barda', 'Zaqatala', 'Shaki', 'Gabala', 'Qusar', 'Masally',
'Hajigabul', 'Manama', 'Muharraq', 'Riffa', 'A`ali', 'Madinat Hamad', 'Isa Town', 'Sitra', 'Budaiya', 'Al Muharraq', 'Al Da`asa', 'Al Riffa', 
'Al Hidd', 'Al Budayyi', 'Al Khaleej', 'Al Jasra', 'Dhaka', 'Chittagong', 'Khulna', 'Sylhet', 'Rajshahi', 'Barisal', 'Rangpur', 'Narayanganj', 
'Comilla', 'Mymensingh', 'Bogra', 'Pabna', 'Jessore', 'Jhenaidah', 'Faridpur', 'Thimphu', 'Paro', 'Punakha', 'Wangdue Phodrang', 'Thimphu (Wangchhu)', 
'Bumthang', 'Gasa', 'Trongsa', 'Mongar', 'Trashigang', 'Tashi Yangtse', 'Lhuentse', 'Samtse', 'Zhemgang', 'Pemagatshel', 'Bandar Seri Begawan', 
'Muara', 'Tutong', 'Seria', 'Kuala Belait', 'Bangar', 'Temburong', 'Kampong Ayer', 'Labu', 'Lumut', 'Telisai', 'Seria (Kuala Belait)', 'Tutong (Kuala Belait)',
'Kuala Lurah', 'Sungai Liang', 'Siem Reap', 'Phnom Penh', 'Sihanoukville', 'Battambang', 'Siem Reap (Angkor)', 'Kampot', 'Kep', 'Pailin', 
'Kampong Cham', 'Kratie', 'Pursat', 'Takeo', 'Svay Rieng', 'Koh Kong','Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chongqing', 'Tianjin', 
'Chengdu', 'Hangzhou', 'Xi`an', 'Harbin', 'Nanjing', 'Qingdao', 'Changsha', 'Shenyang', 'Yangshuo','Nicosia', 'Larnaca', 'Paphos', 'Kyrenia', 'Famagusta', 
'Ayia Napa', 'Protaras', 'Polis Chrysochous', 'Latchi', 'Lemesos', 'Limassol (Paphos)','Limassol', 'Strovolos', 'Engomi',
'Tbilisi', 'Batumi', 'Kutaisi', 'Zugdidi', 'Gori', 'Rustavi', 'Akhaltsikhe', 'Mtskheta', 'Borjomi', 'Telavi', 'Ambrolauri', 'Kutaisi (Gelati)', 'Sighnaghi', 'Kazbegi', 'Mestia',
'New Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Pune', 'Jaipur', 'Varanasi', 'Goa', 'Mysore', 'Indore', 'Jaisalmer', 'Kochi',
  ];
  